// priority: 3
const COMPOUND_ITEMS = [
	"thermal:invar_dust",
	"mekanism:ingot_bronze",
	"thermalendergy:stellarium_ingot",
	"undergarden:froststeel_ingot",
	"superbwarfare:cemented_carbide_ingot",
	"mekanism:dust_bronze",
	"silentcompat:arcmetal_ingot",
	"thermal:enderium_ingot",
	"silentcompat:solarmetal_ingot",
	"minecraft:netherite_ingot",
	"dysonsphere:ingot_smart_alloy",
	"undergarden:regalium_crystal",
	"thermal:electrum_dust",
	"silentgear:azure_electrum_ingot",
	"thermal:invar_ingot",
	"thermal:lumium_ingot",
	"silentcompat:plasteel_ingot",
	"thermal:constantan_ingot",
	"undergarden:cloggrum_ingot",
	"silentgear:azure_electrum_dust",
	"thermal:electrum_ingot",
	"thermal:constantan_dust",
	"thermal:signalum_ingot",
	"thermalendergy:melodium_ingot",
]