// priority: 3
const WEAPONS = [
	{
		id: "superbwarfare:glock_17_blueprint",
		price: 64,
		price_mod: 5,
		static_trade: false,
	},
	{
		id: "superbwarfare:homemade_shotgun_blueprint",
		price: 64,
		price_mod: 5,
		static_trade: false,
	},
	{
		id: "superbwarfare:marlin_blueprint",
		price: 64,
		price_mod: 3,
		static_trade: false,
	},
	{
		id: "superbwarfare:mp_443_blueprint",
		price: 64,
		price_mod: 5,
		static_trade: false,
	},
	{
		id: "superbwarfare:m_1911_blueprint",
		price: 64,
		price_mod: 4,
		static_trade: false,
	},
	{
		id: "superbwarfare:taser_blueprint",
		price: 64,
		price_mod: 3,
		static_trade: false,
	},
	{
		id: "superbwarfare:ak_12_blueprint",
		price: 64,
		price_mod: 8,
		static_trade: false,
	},
	{
		id: "superbwarfare:ak_47_blueprint",
		price: 64,
		price_mod: 6,
		static_trade: false,
	},
	{
		id: "superbwarfare:glock_18_blueprint",
		price: 64,
		price_mod: 6,
		static_trade: false,
	},
	{
		id: "superbwarfare:hk_416_blueprint",
		price: 64,
		price_mod: 8,
		static_trade: false,
	},
	{
		id: "superbwarfare:k_98_blueprint",
		price: 64,
		price_mod: 5,
		static_trade: false,
	},
	{
		id: "superbwarfare:mosin_nagant_blueprint",
		price: 64,
		price_mod: 6,
		static_trade: false,
	},
	{
		id: "superbwarfare:mp_5_blueprint",
		price: 64,
		price_mod: 7,
		static_trade: false,
	},
	{
		id: "superbwarfare:m_2_hb_blueprint",
		price: 64,
		price_mod: 5,
		static_trade: false,
	},
	{
		id: "superbwarfare:m_4_blueprint",
		price: 64,
		price_mod: 7,
		static_trade: false,
	},
	{
		id: "superbwarfare:m_79_blueprint",
		price: 64,
		price_mod: 5,
		static_trade: false,
	},
	{
		id: "superbwarfare:m_870_blueprint",
		price: 64,
		price_mod: 7,
		static_trade: false,
	},
	{
		id: "superbwarfare:qbz_95_blueprint",
		price: 64,
		price_mod: 6,
		static_trade: false,
	},
	{
		id: "superbwarfare:rpg_blueprint",
		price: 64,
		price_mod: 6,
		static_trade: false,
	},
	{
		id: "superbwarfare:sks_blueprint",
		price: 64,
		price_mod: 5,
		static_trade: false,
	},
	{
		id: "superbwarfare:awm_blueprint",
		price: 64,
		price_mod: 9,
		static_trade: false,
	},
	{
		id: "superbwarfare:bocek_blueprint",
		price: 64,
		price_mod: 11,
		static_trade: false,
	},
	{
		id: "superbwarfare:devotion_blueprint",
		price: 64,
		price_mod: 10,
		static_trade: false,
	},
	{
		id: "superbwarfare:hunting_rifle_blueprint",
		price: 64,
		price_mod: 8,
		static_trade: false,
	},
	{
		id: "superbwarfare:igla_9k38_blueprint",
		price: 64,
		price_mod: 10,
		static_trade: false,
	},
	{
		id: "superbwarfare:insidious_blueprint",
		price: 64,
		price_mod: 9,
		static_trade: false,
	},
	{
		id: "superbwarfare:mk_14_blueprint",
		price: 64,
		price_mod: 9,
		static_trade: false,
	},
	{
		id: "superbwarfare:m_60_blueprint",
		price: 64,
		price_mod: 11,
		static_trade: false,
	},
	{
		id: "superbwarfare:m_98b_blueprint",
		price: 64,
		price_mod: 8,
		static_trade: false,
	},
	{
		id: "superbwarfare:qbz_191_blueprint",
		price: 64,
		price_mod: 10,
		static_trade: false,
	},
	{
		id: "superbwarfare:rpk_blueprint",
		price: 64,
		price_mod: 11,
		static_trade: false,
	},
	{
		id: "superbwarfare:svd_blueprint",
		price: 64,
		price_mod: 11,
		static_trade: false,
	},
	{
		id: "superbwarfare:trachelium_blueprint",
		price: 64,
		price_mod: 8,
		static_trade: false,
	},
	{
		id: "superbwarfare:vector_blueprint",
		price: 64,
		price_mod: 10,
		static_trade: false,
	},
	{
		id: "superbwarfare:aa_12_blueprint",
		price: 64,
		price_mod: 17,
		static_trade: false,
	},
	{
		id: "superbwarfare:aurelia_sceptre_blueprint",
		price: 64,
		price_mod: 17,
		static_trade: false,
	},
	{
		id: "superbwarfare:javelin_blueprint",
		price: 64,
		price_mod: 17,
		static_trade: false,
	},
	{
		id: "superbwarfare:minigun_blueprint",
		price: 64,
		price_mod: 17,
		static_trade: false,
	},
	{
		id: "superbwarfare:ntw_20_blueprint",
		price: 64,
		price_mod: 17,
		static_trade: false,
	},
	{
		id: "superbwarfare:secondary_cataclysm_blueprint",
		price: 64,
		price_mod: 17,
		static_trade: false,
	},
	{
		id: "superbwarfare:sentinel_blueprint",
		price: 64,
		price_mod: 17,
		static_trade: false,
	},
]