// priority: 3
const WEAPONS = [
	{
		id: "superbwarfare:glock_17_blueprint",
		price: 11,
		price_mod: 5,
		rarity: 3,
		static_trade: true,
	},
	{
		id: "superbwarfare:marlin_blueprint",
		price: 6,
		price_mod: 4,
		rarity: 2,
		static_trade: true,
	},
	{
		id: "superbwarfare:mp_443_blueprint",
		price: 52,
		price_mod: 4,
		rarity: 3,
		static_trade: false,
	},
	{
		id: "superbwarfare:m_1911_blueprint",
		price: 27,
		price_mod: 4,
		rarity: 2,
		static_trade: false,
	},
	{
		id: "superbwarfare:taser_blueprint",
		price: 10,
		price_mod: 4,
		rarity: 2,
		static_trade: false,
	},
	{
		id: "superbwarfare:ak_12_blueprint",
		price: 43,
		price_mod: 7,
		rarity: 3,
		static_trade: false,
	},
	{
		id: "superbwarfare:ak_47_blueprint",
		price: 61,
		price_mod: 6,
		rarity: 2,
		static_trade: false,
	},
	{
		id: "superbwarfare:glock_18_blueprint",
		price: 20,
		price_mod: 7,
		rarity: 2,
		static_trade: false,
	},
	{
		id: "superbwarfare:hk_416_blueprint",
		price: 43,
		price_mod: 7,
		rarity: 3,
		static_trade: false,
	},
	{
		id: "superbwarfare:k_98_blueprint",
		price: 3,
		price_mod: 5,
		rarity: 1,
		static_trade: true,
	},
	{
		id: "superbwarfare:mosin_nagant_blueprint",
		price: 32,
		price_mod: 6,
		rarity: 1,
		static_trade: true,
	},
	{
		id: "superbwarfare:mp_5_blueprint",
		price: 33,
		price_mod: 7,
		rarity: 3,
		static_trade: false,
	},
	{
		id: "superbwarfare:m_2_hb_blueprint",
		price: 10,
		price_mod: 6,
		rarity: 1,
		static_trade: true,
	},
	{
		id: "superbwarfare:m_4_blueprint",
		price: 31,
		price_mod: 7,
		rarity: 3,
		static_trade: false,
	},
	{
		id: "superbwarfare:m_79_blueprint",
		price: 15,
		price_mod: 5,
		rarity: 1,
		static_trade: false,
	},
	{
		id: "superbwarfare:m_870_blueprint",
		price: 26,
		price_mod: 7,
		rarity: 2,
		static_trade: false,
	},
	{
		id: "superbwarfare:qbz_95_blueprint",
		price: 62,
		price_mod: 6,
		rarity: 2,
		static_trade: false,
	},
	{
		id: "superbwarfare:rpg_blueprint",
		price: 54,
		price_mod: 6,
		rarity: 2,
		static_trade: true,
	},
	{
		id: "superbwarfare:sks_blueprint",
		price: 21,
		price_mod: 6,
		rarity: 1,
		static_trade: true,
	},
	{
		id: "superbwarfare:awm_blueprint",
		price: 43,
		price_mod: 9,
		rarity: 2,
		static_trade: true,
	},
	{
		id: "superbwarfare:bocek_blueprint",
		price: 49,
		price_mod: 10,
		rarity: 3,
		static_trade: false,
	},
	{
		id: "superbwarfare:devotion_blueprint",
		price: 28,
		price_mod: 10,
		rarity: 2,
		static_trade: false,
	},
	{
		id: "superbwarfare:hunting_rifle_blueprint",
		price: 0,
		price_mod: 7,
		rarity: 1,
		static_trade: false,
	},
	{
		id: "superbwarfare:igla_9k38_blueprint",
		price: 41,
		price_mod: 10,
		rarity: 3,
		static_trade: false,
	},
	{
		id: "superbwarfare:insidious_blueprint",
		price: 13,
		price_mod: 10,
		rarity: 2,
		static_trade: false,
	},
	{
		id: "superbwarfare:mk_14_blueprint",
		price: 46,
		price_mod: 9,
		rarity: 2,
		static_trade: false,
	},
	{
		id: "superbwarfare:m_60_blueprint",
		price: 9,
		price_mod: 12,
		rarity: 4,
		static_trade: false,
	},
	{
		id: "superbwarfare:m_98b_blueprint",
		price: 44,
		price_mod: 8,
		rarity: 1,
		static_trade: true,
	},
	{
		id: "superbwarfare:qbz_191_blueprint",
		price: 28,
		price_mod: 10,
		rarity: 2,
		static_trade: false,
	},
	{
		id: "superbwarfare:rpk_blueprint",
		price: 30,
		price_mod: 11,
		rarity: 4,
		static_trade: false,
	},
	{
		id: "superbwarfare:svd_blueprint",
		price: 3,
		price_mod: 11,
		rarity: 3,
		static_trade: false,
	},
	{
		id: "superbwarfare:trachelium_blueprint",
		price: 62,
		price_mod: 8,
		rarity: 1,
		static_trade: false,
	},
	{
		id: "superbwarfare:vector_blueprint",
		price: 39,
		price_mod: 10,
		rarity: 3,
		static_trade: true,
	},
	{
		id: "superbwarfare:aa_12_blueprint",
		price: 12,
		price_mod: 17,
		rarity: 5,
		static_trade: false,
	},
	{
		id: "superbwarfare:aurelia_sceptre_blueprint",
		price: 59,
		price_mod: 17,
		rarity: 1,
		static_trade: false,
	},
	{
		id: "superbwarfare:javelin_blueprint",
		price: 55,
		price_mod: 17,
		rarity: 2,
		static_trade: true,
	},
	{
		id: "superbwarfare:minigun_blueprint",
		price: 54,
		price_mod: 17,
		rarity: 2,
		static_trade: true,
	},
	{
		id: "superbwarfare:ntw_20_blueprint",
		price: 59,
		price_mod: 15,
		rarity: 1,
		static_trade: false,
	},
	{
		id: "superbwarfare:secondary_cataclysm_blueprint",
		price: 44,
		price_mod: 16,
		rarity: 1,
		static_trade: true,
	},
	{
		id: "superbwarfare:sentinel_blueprint",
		price: 15,
		price_mod: 17,
		rarity: 4,
		static_trade: false,
	},
]