// priority: 3
const MATERIALS = {
	REDSTONE: {
		temperature: 1273,
		density: 2000,
		name: "redstone",
		amount: 5.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/redstone",
		normal_ores: [
			"minecraft:redstone_ore",
			"minecraft:deepslate_redstone_ore",
			"deeperdarker:sculk_stone_redstone_ore",
			"deeperdarker:gloomslate_redstone_ore",
		],
		ingot: "minecraft:redstone",
		block: "minecraft:redstone_block",
		clean_slurry: "moremekanismprocessing:clean_redstone",
		dirty_slurry: "moremekanismprocessing:dirty_redstone",
		infusion: "mekanism:redstone",
		fluid: "thermal:redstone",
		enriched: "mekanism:enriched_redstone",
		crystal: "moremekanismprocessing:crystal_redstone",
		dirty: "moremekanismprocessing:dirty_dust_redstone",
		clump: "moremekanismprocessing:clump_redstone",
		shard: "moremekanismprocessing:shard_redstone",
	},
	LAPIS: {
		temperature: 933,
		density: 3000,
		name: "lapis",
		amount: 5.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/lapis",
		normal_ores: [
			"minecraft:lapis_ore",
			"minecraft:deepslate_lapis_ore",
			"ad_astra:glacio_lapis_ore",
			"deeperdarker:sculk_stone_lapis_ore",
			"deeperdarker:gloomslate_lapis_ore",
		],
		ingot: "minecraft:lapis_lazuli",
		block: "minecraft:lapis_block",
		gear: "thermal:lapis_gear",
		dust: "thermal:lapis_dust",
		clean_slurry: "moremekanismprocessing:clean_lapis",
		dirty_slurry: "moremekanismprocessing:dirty_lapis",
		crystal: "moremekanismprocessing:crystal_lapis",
		dirty: "moremekanismprocessing:dirty_dust_lapis",
		clump: "moremekanismprocessing:clump_lapis",
		shard: "moremekanismprocessing:shard_lapis",
		chestplate: "mekanismtools:lapis_lazuli_chestplate",
		leggings: "mekanismtools:lapis_lazuli_leggings",
		helmet: "mekanismtools:lapis_lazuli_helmet",
		boots: "mekanismtools:lapis_lazuli_boots",
		sword: "mekanismtools:lapis_lazuli_sword",
		pickaxe: "mekanismtools:lapis_lazuli_pickaxe",
		hoe: "mekanismtools:lapis_lazuli_hoe",
		axe: "mekanismtools:lapis_lazuli_axe",
		shovel: "mekanismtools:lapis_lazuli_shovel",
	},
	DIAMOND: {
		temperature: 4273,
		density: 2000,
		name: "diamond",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/diamond",
		normal_ores: [
			"minecraft:diamond_ore",
			"minecraft:deepslate_diamond_ore",
			"ad_astra:mars_diamond_ore",
			"ad_astra:venus_diamond_ore",
			"deeperdarker:sculk_stone_diamond_ore",
			"deeperdarker:gloomslate_diamond_ore",
			"undergarden:depthrock_diamond_ore",
			"undergarden:shiverstone_diamond_ore",
		],
		ingot: "minecraft:diamond",
		nugget: "silentgear:diamond_shard",
		block: "minecraft:diamond_block",
		gear: "thermal:diamond_gear",
		dust: "mekanism:dust_diamond",
		clean_slurry: "moremekanismprocessing:clean_diamond",
		dirty_slurry: "moremekanismprocessing:dirty_diamond",
		infusion: "mekanism:diamond",
		enriched: "mekanism:enriched_diamond",
		crystal: "moremekanismprocessing:crystal_diamond",
		dirty: "moremekanismprocessing:dirty_dust_diamond",
		clump: "moremekanismprocessing:clump_diamond",
		shard: "moremekanismprocessing:shard_diamond",
		chestplate: "minecraft:diamond_chestplate",
		leggings: "minecraft:diamond_leggings",
		helmet: "minecraft:diamond_helmet",
		boots: "minecraft:diamond_boots",
		sword: "minecraft:diamond_sword",
		pickaxe: "minecraft:diamond_pickaxe",
		hoe: "minecraft:diamond_hoe",
		axe: "minecraft:diamond_axe",
		shovel: "minecraft:diamond_shovel",
	},
	EMERALD: {
		temperature: 1173,
		density: 4600,
		name: "emerald",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/emerald",
		normal_ores: [
			"minecraft:emerald_ore",
			"minecraft:deepslate_emerald_ore",
			"deeperdarker:sculk_stone_emerald_ore",
			"deeperdarker:gloomslate_emerald_ore",
		],
		ingot: "minecraft:emerald",
		block: "minecraft:emerald_block",
		gear: "thermal:emerald_gear",
		dust: "mekanism:dust_emerald",
		clean_slurry: "moremekanismprocessing:clean_emerald",
		dirty_slurry: "moremekanismprocessing:dirty_emerald",
		crystal: "moremekanismprocessing:crystal_emerald",
		dirty: "moremekanismprocessing:dirty_dust_emerald",
		clump: "moremekanismprocessing:clump_emerald",
		shard: "moremekanismprocessing:shard_emerald",
	},
	NETHERITE: {
		name: "netherite",
		amount: 1.0,
		metal: true,
		upgrade: true,
		normal_ores_tag: "#forge:ores/netherite",
		normal_ores: [
		],
		no_ore_processing: true,
		ingot: "minecraft:netherite_ingot",
		nugget: "thermal:netherite_nugget",
		block: "minecraft:netherite_block",
		plate: "thermal:netherite_plate",
		gear: "thermal:netherite_gear",
		dust: "mekanism:dust_netherite",
		chestplate: "minecraft:netherite_chestplate",
		leggings: "minecraft:netherite_leggings",
		helmet: "minecraft:netherite_helmet",
		boots: "minecraft:netherite_boots",
		sword: "minecraft:netherite_sword",
		pickaxe: "minecraft:netherite_pickaxe",
		hoe: "minecraft:netherite_hoe",
		axe: "minecraft:netherite_axe",
		shovel: "minecraft:netherite_shovel",
	},
	GLOWSTONE: {
		temperature: 3573,
		density: 2000,
		name: "glowstone",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/glowstone",
		normal_ores: [
		],
		ingot: "mekanism:ingot_refined_glowstone",
		nugget: "mekanism:nugget_refined_glowstone",
		block: "mekanism:block_refined_glowstone",
		dust: "minecraft:glowstone_dust",
		fluid: "thermal:glowstone",
		chestplate: "mekanismtools:refined_glowstone_chestplate",
		leggings: "mekanismtools:refined_glowstone_leggings",
		helmet: "mekanismtools:refined_glowstone_helmet",
		boots: "mekanismtools:refined_glowstone_boots",
		sword: "mekanismtools:refined_glowstone_sword",
		pickaxe: "mekanismtools:refined_glowstone_pickaxe",
		hoe: "mekanismtools:refined_glowstone_hoe",
		axe: "mekanismtools:refined_glowstone_axe",
		shovel: "mekanismtools:refined_glowstone_shovel",
	},
	ENDER_PEARL: {
		temperature: 4273,
		density: 1000,
		name: "ender_pearl",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/ender_pearl",
		normal_ores: [
		],
		ingot: "minecraft:ender_pearl",
		dust: "thermal:ender_pearl_dust",
		fluid: "thermal:ender",
	},
	COAL: {
		name: "coal",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/coal",
		normal_ores: [
			"minecraft:coal_ore",
			"minecraft:deepslate_coal_ore",
			"ad_astra:venus_coal_ore",
			"ad_astra:glacio_coal_ore",
			"deeperdarker:sculk_stone_coal_ore",
			"deeperdarker:gloomslate_coal_ore",
			"undergarden:depthrock_coal_ore",
			"undergarden:shiverstone_coal_ore",
		],
		no_ore_processing: true,
		ingot: "minecraft:coal",
		block: "minecraft:coal_block",
		dust: "mekanism:dust_coal",
		clean_slurry: "moremekanismprocessing:clean_coal",
		dirty_slurry: "moremekanismprocessing:dirty_coal",
		crystal: "moremekanismprocessing:crystal_coal",
		dirty: "moremekanismprocessing:dirty_dust_coal",
		clump: "moremekanismprocessing:clump_coal",
		shard: "moremekanismprocessing:shard_coal",
	},
	NETHER_STAR: {
		temperature: 12273,
		name: "nether_star",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/nether_star",
		normal_ores: [
		],
		ingot: "minecraft:nether_star",
		nugget: "silentgear:nether_start_fragment",
	},
	FLUORITE: {
		temperature: 473,
		density: 1000,
		name: "fluorite",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/fluorite",
		normal_ores: [
			"mekanism:fluorite_ore",
			"mekanism:deepslate_fluorite_ore",
			"mekanismaaa:venus_fluorite_ore",
			"mekanismaaa:glacio_fluorite_ore",
			"mekanismaaa:mars_fluorite_ore",
		],
		no_ore_processing: true,
		ingot: "mekanism:fluorite_gem",
		block: "mekanism:block_fluorite",
		dust: "mekanism:dust_fluorite",
	},
	NAQUADAH: {
		temperature: 90273,
		density: 18000,
		name: "naquadah",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/naquadah",
		normal_ores: [
			"sgjourney:naquadah_ore",
			"sgjourney:deepslate_naquadah_ore",
		],
		no_ore_processing: true,
		color: "101811",
		ingot: "mekanism_extras:ingot_naquadah",
		block: "mekanism_extras:block_naquadah",
		raw: "mekanism_extras:raw_naquadah",
		raw_block: "mekanism_extras:block_raw_naquadah",
		plate: "kubejs:naquadah_plate",
		gear: "kubejs:naquadah_gear",
		dust: "mekanism_extras:dust_naquadah",
		clean_slurry: "mekanism_extras:clean_naquadah",
		dirty_slurry: "mekanism_extras:dirty_naquadah",
		fluid: "sgjourney:liquid_naquadah",
		crystal: "mekanism_extras:crystal_naquadah",
		dirty: "mekanism_extras:dirty_dust_naquadah",
		clump: "mekanism_extras:clump_naquadah",
		shard: "mekanism_extras:shard_naquadah",
		chestplate: "sgjourney:naquadah_chestplate",
		leggings: "sgjourney:naquadah_leggings",
		helmet: "sgjourney:naquadah_helmet",
		boots: "sgjourney:naquadah_boots",
		sword: "sgjourney:naquadah_sword",
		pickaxe: "sgjourney:naquadah_pickaxe",
		hoe: "sgjourney:naquadah_hoe",
		axe: "sgjourney:naquadah_axe",
		shovel: "sgjourney:naquadah_shovel",
		plate_generated: true,
		gear_generated: true,
	},
	STEEL: {
		temperature: 1323,
		density: 7000,
		name: "steel",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/steel",
		normal_ores: [
		],
		no_ore_processing: true,
		color: "818282",
		ingot: "mekanism:ingot_steel",
		nugget: "mekanism:nugget_steel",
		block: "mekanism:block_steel",
		plate: "ad_astra:steel_plate",
		gear: "kubejs:steel_gear",
		dust: "mekanism:dust_steel",
		fluid: "kubejs:steel",
		fluid_generated: true,
		chestplate: "mekanismtools:steel_chestplate",
		leggings: "mekanismtools:steel_leggings",
		helmet: "mekanismtools:steel_helmet",
		boots: "mekanismtools:steel_boots",
		sword: "mekanismtools:steel_sword",
		pickaxe: "mekanismtools:steel_pickaxe",
		hoe: "mekanismtools:steel_hoe",
		axe: "mekanismtools:steel_axe",
		shovel: "mekanismtools:steel_shovel",
		gear_generated: true,
	},
	DESH: {
		temperature: 3273,
		density: 5000,
		name: "desh",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/desh",
		normal_ores: [
			"ad_astra:moon_desh_ore",
			"ad_astra:deepslate_desh_ore",
		],
		ingot: "ad_astra:desh_ingot",
		nugget: "ad_astra:desh_nugget",
		block: "ad_astra:desh_block",
		raw: "ad_astra:raw_desh",
		raw_block: "ad_astra:raw_desh_block",
		plate: "ad_astra:desh_plate",
		dust: "moremekanismprocessing:dust_desh",
		clean_slurry: "moremekanismprocessing:clean_desh",
		dirty_slurry: "moremekanismprocessing:dirty_desh",
		crystal: "moremekanismprocessing:crystal_desh",
		dirty: "moremekanismprocessing:dirty_dust_desh",
		clump: "moremekanismprocessing:clump_desh",
		shard: "moremekanismprocessing:shard_desh",
	},
	OSTRUM: {
		temperature: 4273,
		density: 4500,
		name: "ostrum",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/ostrum",
		normal_ores: [
			"ad_astra:mars_ostrum_ore",
			"ad_astra:deepslate_ostrum_ore",
		],
		ingot: "ad_astra:ostrum_ingot",
		nugget: "ad_astra:ostrum_nugget",
		block: "ad_astra:ostrum_block",
		raw: "ad_astra:raw_ostrum",
		raw_block: "ad_astra:raw_ostrum_block",
		plate: "ad_astra:ostrum_plate",
		dust: "moremekanismprocessing:dust_ostrum",
		clean_slurry: "moremekanismprocessing:clean_ostrum",
		dirty_slurry: "moremekanismprocessing:dirty_ostrum",
		crystal: "moremekanismprocessing:crystal_ostrum",
		dirty: "moremekanismprocessing:dirty_dust_ostrum",
		clump: "moremekanismprocessing:clump_ostrum",
		shard: "moremekanismprocessing:shard_ostrum",
	},
	CALORITE: {
		temperature: 8273,
		density: 3600,
		name: "calorite",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/calorite",
		normal_ores: [
			"ad_astra:venus_calorite_ore",
			"ad_astra:deepslate_calorite_ore",
		],
		ingot: "ad_astra:calorite_ingot",
		nugget: "ad_astra:calorite_nugget",
		block: "ad_astra:calorite_block",
		raw: "ad_astra:raw_calorite",
		raw_block: "ad_astra:raw_calorite_block",
		plate: "ad_astra:calorite_plate",
		dust: "moremekanismprocessing:dust_calorite",
		clean_slurry: "moremekanismprocessing:clean_calorite",
		dirty_slurry: "moremekanismprocessing:dirty_calorite",
		crystal: "moremekanismprocessing:crystal_calorite",
		dirty: "moremekanismprocessing:dirty_dust_calorite",
		clump: "moremekanismprocessing:clump_calorite",
		shard: "moremekanismprocessing:shard_calorite",
	},
	ETRIUM: {
		temperature: 3943,
		density: 3000,
		name: "etrium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/etrium",
		normal_ores: [
		],
		ingot: "ad_astra:etrium_ingot",
		nugget: "ad_astra:etrium_nugget",
		block: "ad_astra:etrium_block",
		plate: "ad_astra:etrium_plate",
	},
	BLAZE_GOLD: {
		temperature: 2273,
		density: 15600,
		name: "blaze_gold",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/blaze_gold",
		normal_ores: [
		],
		ingot: "silentgear:blaze_gold_ingot",
		nugget: "silentgear:blaze_gold_nugget",
		block: "silentgear:blaze_gold_block",
		dust: "silentgear:blaze_gold_dust",
	},
	ARCMETAL: {
		temperature: 3273,
		density: 15000,
		name: "arcmetal",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/arcmetal",
		normal_ores: [
			"silentcompat:arcmetal_ore",
		],
		color: "d7f4f4",
		ingot: "silentcompat:arcmetal_ingot",
		nugget: "silentcompat:arcmetal_nugget",
		block: "silentcompat:arcmetal_block",
		raw: "silentcompat:raw_arcmetal",
		plate: "kubejs:arcmetal_plate",
		gear: "kubejs:arcmetal_gear",
		dust: "kubejs:arcmetal_dust",
		clean_slurry: "kubejs:clean_arcmetal",
		dirty_slurry: "kubejs:dirty_arcmetal",
		fluid: "kubejs:arcmetal",
		fluid_generated: true,
		crystal: "kubejs:crystal_arcmetal",
		crystal_generated: true,
		dirty: "kubejs:dirty_dust_arcmetal",
		dirty_generated: true,
		clump: "kubejs:clump_arcmetal",
		clump_generated: true,
		shard: "kubejs:shard_arcmetal",
		shard_generated: true,
		generated_slurry: true,
		plate_generated: true,
		gear_generated: true,
		dust_generated: true,
	},
	VOIDMETAL: {
		temperature: 1173,
		density: 8000,
		name: "voidmetal",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/voidmetal",
		normal_ores: [
			"silentcompat:voidmetal_ore",
		],
		color: "b7a4d3",
		ingot: "silentcompat:voidmetal_ingot",
		nugget: "silentcompat:voidmetal_nugget",
		block: "silentcompat:voidmetal_block",
		raw: "silentcompat:raw_voidmetal",
		plate: "kubejs:voidmetal_plate",
		gear: "kubejs:voidmetal_gear",
		dust: "kubejs:voidmetal_dust",
		clean_slurry: "kubejs:clean_voidmetal",
		dirty_slurry: "kubejs:dirty_voidmetal",
		fluid: "kubejs:voidmetal",
		fluid_generated: true,
		crystal: "kubejs:crystal_voidmetal",
		crystal_generated: true,
		dirty: "kubejs:dirty_dust_voidmetal",
		dirty_generated: true,
		clump: "kubejs:clump_voidmetal",
		clump_generated: true,
		shard: "kubejs:shard_voidmetal",
		shard_generated: true,
		generated_slurry: true,
		plate_generated: true,
		gear_generated: true,
		dust_generated: true,
	},
	SOLARMETAL: {
		temperature: 773,
		density: 30000,
		name: "solarmetal",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/solarmetal",
		normal_ores: [
			"silentcompat:solarmetal_ore",
		],
		color: "fecda4",
		ingot: "silentcompat:solarmetal_ingot",
		nugget: "silentcompat:solarmetal_nugget",
		block: "silentcompat:solarmetal_block",
		raw: "silentcompat:raw_solarmetal",
		plate: "kubejs:solarmetal_plate",
		gear: "kubejs:solarmetal_gear",
		dust: "kubejs:solarmetal_dust",
		clean_slurry: "kubejs:clean_solarmetal",
		dirty_slurry: "kubejs:dirty_solarmetal",
		fluid: "kubejs:solarmetal",
		fluid_generated: true,
		crystal: "kubejs:crystal_solarmetal",
		crystal_generated: true,
		dirty: "kubejs:dirty_dust_solarmetal",
		dirty_generated: true,
		clump: "kubejs:clump_solarmetal",
		clump_generated: true,
		shard: "kubejs:shard_solarmetal",
		shard_generated: true,
		generated_slurry: true,
		plate_generated: true,
		gear_generated: true,
		dust_generated: true,
	},
	PLASTEEL: {
		temperature: 2073,
		density: 12000,
		name: "plasteel",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/plasteel",
		normal_ores: [
			"silentcompat:plasteel_ore",
		],
		color: "302F74",
		ingot: "silentcompat:plasteel_ingot",
		nugget: "silentcompat:plasteel_nugget",
		block: "silentcompat:plasteel_block",
		raw: "silentcompat:raw_plasteel",
		plate: "kubejs:plasteel_plate",
		gear: "kubejs:plasteel_gear",
		dust: "kubejs:plasteel_dust",
		clean_slurry: "kubejs:clean_plasteel",
		dirty_slurry: "kubejs:dirty_plasteel",
		fluid: "kubejs:plasteel",
		fluid_generated: true,
		crystal: "kubejs:crystal_plasteel",
		crystal_generated: true,
		dirty: "kubejs:dirty_dust_plasteel",
		dirty_generated: true,
		clump: "kubejs:clump_plasteel",
		clump_generated: true,
		shard: "kubejs:shard_plasteel",
		shard_generated: true,
		generated_slurry: true,
		plate_generated: true,
		gear_generated: true,
		dust_generated: true,
	},
	BORT: {
		temperature: 2273,
		density: 1000,
		name: "bort",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/bort",
		normal_ores: [
			"silentgear:bort_ore",
			"silentgear:deepslate_bort_ore",
		],
		ingot: "silentgear:bort",
		block: "silentgear:bort_block",
		dust: "moremekanismprocessing:dust_bort",
		clean_slurry: "moremekanismprocessing:clean_bort",
		dirty_slurry: "moremekanismprocessing:dirty_bort",
		crystal: "moremekanismprocessing:crystal_bort",
		dirty: "moremekanismprocessing:dirty_dust_bort",
		clump: "moremekanismprocessing:clump_bort",
		shard: "moremekanismprocessing:shard_bort",
	},
	CRIMSON_IRON: {
		temperature: 4173,
		density: 8100,
		name: "crimson_iron",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/crimson_iron",
		normal_ores: [
			"silentgear:crimson_iron_ore",
			"silentgear:blackstone_crimson_iron_ore",
		],
		ingot: "silentgear:crimson_iron_ingot",
		nugget: "silentgear:crimson_iron_nugget",
		block: "silentgear:crimson_iron_block",
		raw: "silentgear:raw_crimson_iron",
		raw_block: "silentgear:raw_crimson_iron_block",
		dust: "silentgear:crimson_iron_dust",
		clean_slurry: "moremekanismprocessing:clean_crimson_iron",
		dirty_slurry: "moremekanismprocessing:dirty_crimson_iron",
		crystal: "moremekanismprocessing:crystal_crimson_iron",
		dirty: "moremekanismprocessing:dirty_dust_crimson_iron",
		clump: "moremekanismprocessing:clump_crimson_iron",
		shard: "moremekanismprocessing:shard_crimson_iron",
	},
	AZURE_SILVER: {
		temperature: 1173,
		density: 6000,
		name: "azure_silver",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/azure_silver",
		normal_ores: [
			"silentgear:azure_silver_ore",
		],
		ingot: "silentgear:azure_silver_ingot",
		nugget: "silentgear:azure_silver_nugget",
		block: "silentgear:azure_silver_block",
		raw: "silentgear:raw_azure_silver",
		raw_block: "silentgear:raw_azure_silver_block",
		dust: "silentgear:azure_silver_dust",
		clean_slurry: "moremekanismprocessing:clean_azure_silver",
		dirty_slurry: "moremekanismprocessing:dirty_azure_silver",
		crystal: "moremekanismprocessing:crystal_azure_silver",
		dirty: "moremekanismprocessing:dirty_dust_azure_silver",
		clump: "moremekanismprocessing:clump_azure_silver",
		shard: "moremekanismprocessing:shard_azure_silver",
	},
	BRONZE: {
		temperature: 1273,
		density: 8700,
		name: "bronze",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/bronze",
		normal_ores: [
		],
		ingot: "mekanism:ingot_bronze",
		nugget: "mekanism:nugget_bronze",
		block: "mekanism:block_bronze",
		plate: "thermal:bronze_plate",
		gear: "thermal:bronze_gear",
		dust: "mekanism:dust_bronze",
		chestplate: "mekanismtools:bronze_chestplate",
		leggings: "mekanismtools:bronze_leggings",
		helmet: "mekanismtools:bronze_helmet",
		boots: "mekanismtools:bronze_boots",
		sword: "mekanismtools:bronze_sword",
		pickaxe: "mekanismtools:bronze_pickaxe",
		hoe: "mekanismtools:bronze_hoe",
		axe: "mekanismtools:bronze_axe",
		shovel: "mekanismtools:bronze_shovel",
	},
	TYRIAN_STEEL: {
		temperature: 6273,
		density: 12000,
		name: "tyrian_steel",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/tyrian_steel",
		normal_ores: [
		],
		ingot: "silentgear:tyrian_steel_ingot",
		nugget: "silentgear:tyrian_steel_nugget",
		block: "silentgear:tyrian_steel_block",
		dust: "silentgear:tyrian_steel_dust",
	},
	MIDNIGHT_IRON: {
		temperature: 4273,
		density: 2000,
		name: "midnight_iron",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/midnight_iron",
		normal_ores: [
		],
		ingot: "silentcompat:midnight_iron_ingot",
		nugget: "silentcompat:midnight_iron_nugget",
		block: "silentcompat:midnight_iron_block",
	},
	SCULK_ALLOY: {
		temperature: 2273,
		density: 7100,
		name: "sculk_alloy",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/sculk_alloy",
		normal_ores: [
		],
		ingot: "silentcompat:sculk_alloy_ingot",
		nugget: "silentcompat:sculk_alloy_nugget",
		block: "silentcompat:sculk_alloy_block",
	},
	BUNNY_STEEL: {
		temperature: 1873,
		density: 9100,
		name: "bunny_steel",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/bunny_steel",
		normal_ores: [
		],
		ingot: "silentcompat:bunny_steel_ingot",
		nugget: "silentcompat:bunny_steel_nugget",
		block: "silentcompat:bunny_steel_block",
	},
	CAPSID_ALLOY: {
		temperature: 6273,
		density: 9100,
		name: "capsid_alloy",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/capsid_alloy",
		normal_ores: [
		],
		ingot: "silentcompat:capsid_alloy_ingot",
		nugget: "silentcompat:capsid_alloy_nugget",
		block: "silentcompat:capsid_alloy_block",
	},
	SOURCE_STEEL: {
		temperature: 5273,
		density: 7100,
		name: "source_steel",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/source_steel",
		normal_ores: [
		],
		ingot: "silentcompat:source_steel_ingot",
		nugget: "silentcompat:source_steel_nugget",
		block: "silentcompat:source_steel_block",
	},
	CRIMSON_STEEL: {
		temperature: 5273,
		density: 7100,
		name: "crimson_steel",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/crimson_steel",
		normal_ores: [
		],
		ingot: "silentgear:crimson_steel_ingot",
		nugget: "silentgear:crimson_steel_nugget",
		block: "silentgear:crimson_steel_block",
		dust: "silentgear:crimson_steel_dust",
	},
	REGALIUM: {
		name: "regalium",
		amount: 1.0,
		metal: false,
		upgrade: true,
		normal_ores_tag: "#forge:ores/regalium",
		normal_ores: [
			"undergarden:depthrock_regalium_ore",
			"undergarden:shiverstone_regalium_ore",
		],
		color: "EACAA4",
		ingot: "undergarden:regalium_crystal",
		block: "undergarden:regalium_block",
		clean_slurry: "kubejs:clean_regalium",
		dirty_slurry: "kubejs:dirty_regalium",
		crystal: "kubejs:crystal_regalium",
		crystal_generated: true,
		dirty: "kubejs:dirty_dust_regalium",
		dirty_generated: true,
		clump: "kubejs:clump_regalium",
		clump_generated: true,
		shard: "kubejs:shard_regalium",
		shard_generated: true,
		generated_slurry: true,
	},
	CLOGGRUM: {
		temperature: 3073,
		density: 10000,
		name: "cloggrum",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/cloggrum",
		normal_ores: [
			"undergarden:depthrock_cloggrum_ore",
			"undergarden:shiverstone_cloggrum_ore",
		],
		color: "B89B7A",
		ingot: "undergarden:cloggrum_ingot",
		nugget: "undergarden:cloggrum_nugget",
		block: "undergarden:cloggrum_block",
		raw: "undergarden:raw_cloggrum",
		raw_block: "undergarden:raw_cloggrum_block",
		plate: "kubejs:cloggrum_plate",
		gear: "kubejs:cloggrum_gear",
		dust: "kubejs:cloggrum_dust",
		clean_slurry: "kubejs:clean_cloggrum",
		dirty_slurry: "kubejs:dirty_cloggrum",
		fluid: "kubejs:cloggrum",
		fluid_generated: true,
		crystal: "kubejs:crystal_cloggrum",
		crystal_generated: true,
		dirty: "kubejs:dirty_dust_cloggrum",
		dirty_generated: true,
		clump: "kubejs:clump_cloggrum",
		clump_generated: true,
		shard: "kubejs:shard_cloggrum",
		shard_generated: true,
		chestplate: "undergarden:cloggrum_chestplate",
		leggings: "undergarden:cloggrum_leggings",
		helmet: "undergarden:cloggrum_helmet",
		boots: "undergarden:cloggrum_boots",
		sword: "undergarden:cloggrum_sword",
		pickaxe: "undergarden:cloggrum_pickaxe",
		hoe: "undergarden:cloggrum_hoe",
		axe: "undergarden:cloggrum_axe",
		shovel: "undergarden:cloggrum_shovel",
		generated_slurry: true,
		plate_generated: true,
		gear_generated: true,
		dust_generated: true,
	},
	FROSTSTEEL: {
		temperature: 9273,
		density: 5000,
		name: "froststeel",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/froststeel",
		normal_ores: [
			"undergarden:shiverstone_froststeel_ore",
		],
		color: "8EB7DD",
		ingot: "undergarden:froststeel_ingot",
		nugget: "undergarden:froststeel_nugget",
		block: "undergarden:froststeel_block",
		raw: "undergarden:raw_froststeel",
		raw_block: "undergarden:raw_froststeel_block",
		plate: "kubejs:froststeel_plate",
		gear: "kubejs:froststeel_gear",
		dust: "kubejs:froststeel_dust",
		clean_slurry: "kubejs:clean_froststeel",
		dirty_slurry: "kubejs:dirty_froststeel",
		fluid: "kubejs:froststeel",
		fluid_generated: true,
		crystal: "kubejs:crystal_froststeel",
		crystal_generated: true,
		dirty: "kubejs:dirty_dust_froststeel",
		dirty_generated: true,
		clump: "kubejs:clump_froststeel",
		clump_generated: true,
		shard: "kubejs:shard_froststeel",
		shard_generated: true,
		chestplate: "undergarden:froststeel_chestplate",
		leggings: "undergarden:froststeel_leggings",
		helmet: "undergarden:froststeel_helmet",
		boots: "undergarden:froststeel_boots",
		sword: "undergarden:froststeel_sword",
		pickaxe: "undergarden:froststeel_pickaxe",
		hoe: "undergarden:froststeel_hoe",
		axe: "undergarden:froststeel_axe",
		shovel: "undergarden:froststeel_shovel",
		generated_slurry: true,
		plate_generated: true,
		gear_generated: true,
		dust_generated: true,
	},
	UTHERIUM: {
		temperature: 973,
		density: 7000,
		name: "utherium",
		amount: 2.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/utherium",
		normal_ores: [
			"undergarden:depthrock_utherium_ore",
			"undergarden:shiverstone_utherium_ore",
			"undergarden:tremblecrust_utherium_ore",
		],
		color: "FC7768",
		ingot: "undergarden:utherium_crystal",
		nugget: "undergarden:utheric_shard",
		block: "undergarden:utherium_block",
		clean_slurry: "kubejs:clean_utherium",
		dirty_slurry: "kubejs:dirty_utherium",
		fluid: "kubejs:utherium",
		fluid_generated: true,
		crystal: "kubejs:crystal_utherium",
		crystal_generated: true,
		dirty: "kubejs:dirty_dust_utherium",
		dirty_generated: true,
		clump: "kubejs:clump_utherium",
		clump_generated: true,
		shard: "kubejs:shard_utherium",
		shard_generated: true,
		chestplate: "undergarden:utherium_chestplate",
		leggings: "undergarden:utherium_leggings",
		helmet: "undergarden:utherium_helmet",
		boots: "undergarden:utherium_boots",
		sword: "undergarden:utherium_sword",
		pickaxe: "undergarden:utherium_pickaxe",
		hoe: "undergarden:utherium_hoe",
		axe: "undergarden:utherium_axe",
		shovel: "undergarden:utherium_shovel",
		generated_slurry: true,
	},
	FORGOTTEN: {
		temperature: 9273,
		density: 7100,
		name: "forgotten",
		amount: 1.0,
		metal: true,
		upgrade: true,
		normal_ores_tag: "#forge:ores/forgotten",
		normal_ores: [
		],
		ingot: "undergarden:forgotten_ingot",
		nugget: "undergarden:forgotten_nugget",
		block: "undergarden:forgotten_block",
		sword: "undergarden:forgotten_sword",
		pickaxe: "undergarden:forgotten_pickaxe",
		hoe: "undergarden:forgotten_hoe",
		axe: "undergarden:forgotten_axe",
		shovel: "undergarden:forgotten_shovel",
	},
	SKY_STEEL: {
		name: "sky_steel",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/sky_steel",
		normal_ores: [
		],
		ingot: "megacells:sky_steel_ingot",
		block: "megacells:sky_steel_block",
	},
	RUBY: {
		temperature: 933,
		density: 4000,
		name: "ruby",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/ruby",
		normal_ores: [
			"thermal_and_space:venus_ruby_ore",
			"thermal:ruby_ore",
		],
		ingot: "thermal:ruby",
		block: "thermal:ruby_block",
		gear: "thermal:ruby_gear",
		dust: "thermal:ruby_dust",
		clean_slurry: "moremekanismprocessing:clean_ruby",
		dirty_slurry: "moremekanismprocessing:dirty_ruby",
		crystal: "moremekanismprocessing:crystal_ruby",
		dirty: "moremekanismprocessing:dirty_dust_ruby",
		clump: "moremekanismprocessing:clump_ruby",
		shard: "moremekanismprocessing:shard_ruby",
	},
	SAPPHIRE: {
		temperature: 1173,
		density: 5000,
		name: "sapphire",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/sapphire",
		normal_ores: [
			"thermal_and_space:glacio_sapphire_ore",
			"thermal:sapphire_ore",
		],
		ingot: "thermal:sapphire",
		block: "thermal:sapphire_block",
		gear: "thermal:sapphire_gear",
		dust: "thermal:sapphire_dust",
		clean_slurry: "moremekanismprocessing:clean_sapphire",
		dirty_slurry: "moremekanismprocessing:dirty_sapphire",
		crystal: "moremekanismprocessing:crystal_sapphire",
		dirty: "moremekanismprocessing:dirty_dust_sapphire",
		clump: "moremekanismprocessing:clump_sapphire",
		shard: "moremekanismprocessing:shard_sapphire",
	},
	GREEN_SAPPHIRE: {
		temperature: 1173,
		density: 4000,
		name: "green_sapphire",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/green_sapphire",
		normal_ores: [
		],
		ingot: "moremekanismprocessing:gem_green_sapphire",
		dust: "moremekanismprocessing:dust_green_sapphire",
		clean_slurry: "moremekanismprocessing:clean_green_sapphire",
		dirty_slurry: "moremekanismprocessing:dirty_green_sapphire",
	},
	COMPRESSED_IRON: {
		temperature: 5273,
		density: 16000,
		name: "compressed_iron",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/compressed_iron",
		normal_ores: [
		],
		ingot: "pneumaticcraft:ingot_iron_compressed",
		block: "pneumaticcraft:compressed_iron_block",
		gear: "pneumaticcraft:compressed_iron_gear",
		chestplate: "pneumaticcraft:compressed_iron_chestplate",
		leggings: "pneumaticcraft:compressed_iron_leggings",
		helmet: "pneumaticcraft:compressed_iron_helmet",
		boots: "pneumaticcraft:compressed_iron_boots",
	},
	ENDERIUM: {
		temperature: 6273,
		density: 11000,
		name: "enderium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/enderium",
		normal_ores: [
		],
		color: "baf6f1",
		ingot: "thermal:enderium_ingot",
		nugget: "thermal:enderium_nugget",
		block: "thermal:enderium_block",
		plate: "thermal:enderium_plate",
		gear: "thermal:enderium_gear",
		dust: "thermal:enderium_dust",
		fluid: "kubejs:enderium",
		fluid_generated: true,
	},
	MELODIUM: {
		temperature: 9273,
		density: 9000,
		name: "melodium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/melodium",
		normal_ores: [
		],
		color: "e9cef8",
		ingot: "thermalendergy:melodium_ingot",
		nugget: "thermalendergy:melodium_nugget",
		block: "thermalendergy:melodium_block",
		plate: "thermalendergy:melodium_plate",
		gear: "thermalendergy:melodium_gear",
		dust: "thermalendergy:melodium_dust",
		fluid: "kubejs:melodium",
		fluid_generated: true,
	},
	STELLARIUM: {
		temperature: 26273,
		density: 6000,
		name: "stellarium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/stellarium",
		normal_ores: [
		],
		color: "fdfed3",
		ingot: "thermalendergy:stellarium_ingot",
		nugget: "thermalendergy:stellarium_nugget",
		block: "thermalendergy:stellarium_block",
		plate: "thermalendergy:stellarium_plate",
		gear: "thermalendergy:stellarium_gear",
		dust: "thermalendergy:stellarium_dust",
		fluid: "kubejs:stellarium",
		fluid_generated: true,
	},
	CEMENTED_CARBIDE: {
		temperature: 6873,
		density: 4000,
		name: "cemented_carbide",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/cemented_carbide",
		normal_ores: [
		],
		ingot: "superbwarfare:cemented_carbide_ingot",
		block: "superbwarfare:cemented_carbide_block",
		dust: "superbwarfare:raw_cemented_carbide_powder",
	},
	PLASTIC: {
		temperature: 623,
		density: 1000,
		name: "plastic",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/plastic",
		normal_ores: [
		],
		ingot: "pneumaticcraft:plastic",
		fluid: "pneumaticcraft:plastic",
	},
	ANTIMATTER: {
		name: "antimatter",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/antimatter",
		normal_ores: [
		],
		ingot: "mekanism:pellet_antimatter",
		gas: "mekanism:antimatter",
	},
	SMART_ALLOY: {
		name: "smart_alloy",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/smart_alloy",
		normal_ores: [
		],
		ingot: "dysonsphere:ingot_smart_alloy",
	},
	EXTRATERRESTRIAL_STEEL: {
		temperature: 2573,
		density: 3000,
		name: "extraterrestrial_steel",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/extraterrestrial_steel",
		normal_ores: [
			"clanginghowl:extraterrestrial_steel_ore",
		],
		color: "aaaaaa",
		ingot: "clanginghowl:extraterrestrial_steel_ingot",
		nugget: "clanginghowl:extraterrestrial_steel_nugget",
		block: "clanginghowl:extraterrestrial_steel_block",
		raw: "clanginghowl:extraterrestrial_steel",
		raw_block: "clanginghowl:raw_extraterrestrial_steel_block",
		plate: "clanginghowl:extraterrestrial_steel_plate",
		gear: "kubejs:extraterrestrial_steel_gear",
		dust: "kubejs:extraterrestrial_steel_dust",
		clean_slurry: "kubejs:clean_extraterrestrial_steel",
		dirty_slurry: "kubejs:dirty_extraterrestrial_steel",
		fluid: "kubejs:extraterrestrial_steel",
		fluid_generated: true,
		crystal: "kubejs:crystal_extraterrestrial_steel",
		crystal_generated: true,
		dirty: "kubejs:dirty_dust_extraterrestrial_steel",
		dirty_generated: true,
		clump: "kubejs:clump_extraterrestrial_steel",
		clump_generated: true,
		shard: "kubejs:shard_extraterrestrial_steel",
		shard_generated: true,
		generated_slurry: true,
		gear_generated: true,
		dust_generated: true,
	},
	NICKEL: {
		name: "nickel",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/nickel",
		normal_ores: [
			"thermal_and_space:glacio_nickel_ore",
			"thermal_and_space:mars_nickel_ore",
			"thermal_and_space:mercury_nickel_ore",
			"thermal_and_space:moon_nickel_ore",
			"thermal_and_space:venus_nickel_ore",
			"thermal:nickel_ore",
			"thermal:deepslate_nickel_ore",
		],
		chemical: "nickel",
		color: "62764c",
		ingot: "thermal:nickel_ingot",
		nugget: "thermal:nickel_nugget",
		block: "thermal:nickel_block",
		raw: "thermal:raw_nickel",
		raw_block: "thermal:raw_nickel_block",
		plate: "thermal:nickel_plate",
		gear: "thermal:nickel_gear",
		dust: "thermal:nickel_dust",
		clean_slurry: "moremekanismprocessing:clean_nickel",
		dirty_slurry: "moremekanismprocessing:dirty_nickel",
		infusion: "kubejs:nickel",
		temperature: 1728.0,
		fluid: "kubejs:nickel",
		gas: "kubejs:nickel",
		crystal: "moremekanismprocessing:crystal_nickel",
		dirty: "moremekanismprocessing:dirty_dust_nickel",
		clump: "moremekanismprocessing:clump_nickel",
		shard: "moremekanismprocessing:shard_nickel",
	},
	INVAR: {
		temperature: 1698,
		density: 8130,
		name: "invar",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/invar",
		normal_ores: [
		],
		color: "e1e5e0",
		ingot: "thermal:invar_ingot",
		nugget: "thermal:invar_nugget",
		block: "thermal:invar_block",
		plate: "thermal:invar_plate",
		gear: "thermal:invar_gear",
		dust: "thermal:invar_dust",
		fluid: "kubejs:invar",
		fluid_generated: true,
	},
	ELECTRUM: {
		temperature: 1273,
		density: 15600,
		name: "electrum",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/electrum",
		normal_ores: [
		],
		color: "f3ebba",
		ingot: "thermal:electrum_ingot",
		nugget: "thermal:electrum_nugget",
		block: "thermal:electrum_block",
		plate: "thermal:electrum_plate",
		gear: "thermal:electrum_gear",
		dust: "thermal:electrum_dust",
		fluid: "kubejs:electrum",
		fluid_generated: true,
	},
	AZURE_ELECTRUM: {
		temperature: 1673,
		density: 20600,
		name: "azure_electrum",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/azure_electrum",
		normal_ores: [
		],
		color: "a2baf0",
		ingot: "silentgear:azure_electrum_ingot",
		nugget: "silentgear:azure_electrum_nugget",
		block: "silentgear:azure_electrum_block",
		plate: "kubejs:azure_electrum_plate",
		gear: "kubejs:azure_electrum_gear",
		dust: "silentgear:azure_electrum_dust",
		fluid: "kubejs:azure_electrum",
		fluid_generated: true,
		plate_generated: true,
		gear_generated: true,
	},
	CONSTANTAN: {
		temperature: 1533,
		density: 8900,
		name: "constantan",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/constantan",
		normal_ores: [
		],
		color: "c2a28e",
		ingot: "thermal:constantan_ingot",
		nugget: "thermal:constantan_nugget",
		block: "thermal:constantan_block",
		plate: "thermal:constantan_plate",
		gear: "thermal:constantan_gear",
		dust: "thermal:constantan_dust",
		fluid: "kubejs:constantan",
		fluid_generated: true,
	},
	SIGNALUM: {
		temperature: 2073,
		density: 7000,
		name: "signalum",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/signalum",
		normal_ores: [
		],
		color: "ff8080",
		ingot: "thermal:signalum_ingot",
		nugget: "thermal:signalum_nugget",
		block: "thermal:signalum_block",
		plate: "thermal:signalum_plate",
		gear: "thermal:signalum_gear",
		dust: "thermal:signalum_dust",
		fluid: "kubejs:signalum",
		fluid_generated: true,
	},
	PRISMALIUM: {
		temperature: 1373,
		density: 4000,
		name: "prismalium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/prismalium",
		normal_ores: [
		],
		color: "a9cbc0",
		ingot: "thermalendergy:prismalium_ingot",
		nugget: "thermalendergy:prismalium_nugget",
		block: "thermalendergy:prismalium_block",
		plate: "thermalendergy:prismalium_plate",
		gear: "thermalendergy:prismalium_gear",
		dust: "thermalendergy:prismalium_dust",
		fluid: "kubejs:prismalium",
		fluid_generated: true,
	},
	LUMIUM: {
		temperature: 1073,
		density: 5000,
		name: "lumium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/lumium",
		normal_ores: [
		],
		color: "fef5c9",
		ingot: "thermal:lumium_ingot",
		nugget: "thermal:lumium_nugget",
		block: "thermal:lumium_block",
		plate: "thermal:lumium_plate",
		gear: "thermal:lumium_gear",
		dust: "thermal:lumium_dust",
		fluid: "kubejs:lumium",
		fluid_generated: true,
	},
	AMETHYST: {
		temperature: 1698,
		density: 5130,
		name: "amethyst",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/amethyst",
		normal_ores: [
		],
		color: "dbc6f1",
		ingot: "minecraft:amethyst_shard",
		nugget: "minecraft:amethyst_shard",
		block: "minecraft:amethyst_block",
		dust: "moremekanismprocessing:dust_amethyst",
		clean_slurry: "moremekanismprocessing:clean_amethyst",
		dirty_slurry: "moremekanismprocessing:dirty_amethyst",
		fluid: "kubejs:amethyst",
		fluid_generated: true,
	},
	APATITE: {
		temperature: 933,
		density: 6000,
		name: "apatite",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/apatite",
		normal_ores: [
			"thermal_and_space:glacio_apatite_ore",
			"thermal:apatite_ore",
			"thermal:deepslate_apatite_ore",
		],
		ingot: "thermal:apatite",
		block: "thermal:apatite_block",
		dust: "thermal:apatite_dust",
		clean_slurry: "moremekanismprocessing:clean_apatite",
		dirty_slurry: "moremekanismprocessing:dirty_apatite",
		crystal: "moremekanismprocessing:crystal_apatite",
		dirty: "moremekanismprocessing:dirty_dust_apatite",
		clump: "moremekanismprocessing:clump_apatite",
		shard: "moremekanismprocessing:shard_apatite",
	},
	CINNABAR: {
		temperature: 1173,
		density: 8000,
		name: "cinnabar",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/cinnabar",
		normal_ores: [
			"thermal_and_space:glacio_cinnabar_ore",
			"thermal_and_space:mercury_cinnabar_ore",
			"thermal_and_space:moon_cinnabar_ore",
			"thermal_and_space:venus_cinnabar_ore",
			"thermal:cinnabar_ore",
			"thermal:deepslate_cinnabar_ore",
		],
		ingot: "thermal:cinnabar",
		block: "thermal:cinnabar_block",
		dust: "thermal:cinnabar_dust",
		clean_slurry: "moremekanismprocessing:clean_cinnabar",
		dirty_slurry: "moremekanismprocessing:dirty_cinnabar",
		crystal: "moremekanismprocessing:crystal_cinnabar",
		dirty: "moremekanismprocessing:dirty_dust_cinnabar",
		clump: "moremekanismprocessing:clump_cinnabar",
		shard: "moremekanismprocessing:shard_cinnabar",
	},
	NITER: {
		temperature: 581,
		density: 2200,
		name: "niter",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/niter",
		normal_ores: [
			"thermal_and_space:glacio_niter_ore",
			"thermal_and_space:mars_niter_ore",
			"thermal_and_space:mercury_niter_ore",
			"thermal_and_space:moon_niter_ore",
			"thermal_and_space:venus_niter_ore",
			"thermal:niter_ore",
			"thermal:deepslate_niter_ore",
		],
		ingot: "thermal:niter",
		block: "thermal:niter_block",
		dust: "thermal:niter_dust",
		clean_slurry: "moremekanismprocessing:clean_niter",
		dirty_slurry: "moremekanismprocessing:dirty_niter",
		crystal: "moremekanismprocessing:crystal_niter",
		dirty: "moremekanismprocessing:dirty_dust_niter",
		clump: "moremekanismprocessing:clump_niter",
		shard: "moremekanismprocessing:shard_niter",
	},
	TITANIUM_BERYLLIDE: {
		name: "titanium_beryllide",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/titanium_beryllide",
		normal_ores: [
		],
	},
	FERRUM: {
		temperature: 2698,
		density: 3130,
		name: "ferrum",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/ferrum",
		normal_ores: [
			"macabre:ferrum_ore",
		],
		ingot: "macabre:ferrum_ingot",
		block: "macabre:ferrum_block",
		raw: "macabre:raw_ferrum",
		chestplate: "macabre:ferrum_armor_chestplate",
		leggings: "macabre:ferrum_armor_leggings",
		helmet: "macabre:ferrum_armor_helmet",
		boots: "macabre:ferrum_armor_boots",
		sword: "macabre:ferrum_sword",
		pickaxe: "macabre:ferrum_pickaxe",
		hoe: "macabre:ferrum_hoe",
		axe: "macabre:ferrum_axe",
		shovel: "macabre:ferrum_shovel",
	},
	PLASMA: {
		name: "plasma",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/plasma",
		normal_ores: [
			"macabre:plasma_ore",
		],
		ingot: "macabre:plasma",
		raw: "macabre:raw_plasma",
		chestplate: "macabre:plasma_armor_chestplate",
		leggings: "macabre:plasma_armor_leggings",
		helmet: "macabre:plasma_armor_helmet",
		boots: "macabre:plasma_armor_boots",
		sword: "macabre:plasma_sword",
		pickaxe: "macabre:plasma_pickaxe",
		hoe: "macabre:plasma_hoe",
		axe: "macabre:plasma_axe",
		shovel: "macabre:plasma_shovel",
	},
	FAT: {
		name: "fat",
		amount: 1.0,
		metal: false,
		upgrade: false,
		normal_ores_tag: "#forge:ores/fat",
		normal_ores: [
			"macabre:fat_ore",
		],
		ingot: "macabre:fat",
		block: "macabre:fat_block",
	},
	BLACK_STEEL: {
		name: "black_steel",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/black_steel",
		normal_ores: [
		],
		ingot: "cataclysm:black_steel_ingot",
		nugget: "cataclysm:black_steel_nugget",
		block: "cataclysm:black_steel_block",
		sword: "cataclysm:black_steel_sword",
		pickaxe: "cataclysm:black_steel_pickaxe",
		hoe: "cataclysm:black_steel_hoe",
		axe: "cataclysm:black_steel_axe",
		shovel: "cataclysm:black_steel_shovel",
	},
	LITHIUM: {
		name: "lithium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/lithium",
		normal_ores: [
		],
		color: "8F243E",
		chemical: "lithium",
		ingot: "moremekanismprocessing:lithium_ingot",
		nugget: "moremekanismprocessing:lithium_nugget",
		block: "chemlib:lithium_metal_block",
		plate: "chemlib:lithium_plate",
		dust: "mekanism:dust_lithium",
		clean_slurry: "moremekanismprocessing:clean_dilithium",
		dirty_slurry: "moremekanismprocessing:dirty_dilithium",
		temperature: 453.65,
		fluid: "mekanism:lithium",
		gas: "mekanism:lithium",
	},
	BERYLLIUM: {
		name: "beryllium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/beryllium",
		normal_ores: [
		],
		color: "21A17E",
		chemical: "beryllium",
		ingot: "chemlib:beryllium_ingot",
		nugget: "chemlib:beryllium_nugget",
		block: "chemlib:beryllium_metal_block",
		plate: "chemlib:beryllium_plate",
		dust: "chemlib:beryllium_dust",
		temperature: 1560.0,
		fluid: "mekanismelements:beryllium",
		gas: "mekanismelements:beryllium",
	},
	BORON: {
		name: "boron",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/boron",
		normal_ores: [
		],
		color: "3E4A60",
		chemical: "boron",
		ingot: "moremekanismprocessing:boron_ingot",
		nugget: "moremekanismprocessing:boron_nugget",
		dust: "moremekanismprocessing:dust_boron",
		temperature: 2349.0,
		fluid: "kubejs:boron",
		gas: "kubejs:boron",
	},
	SODIUM: {
		name: "sodium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/sodium",
		normal_ores: [
		],
		color: "d3c683",
		chemical: "sodium",
		ingot: "chemlib:sodium_ingot",
		nugget: "chemlib:sodium_nugget",
		block: "chemlib:sodium_metal_block",
		plate: "chemlib:sodium_plate",
		dust: "chemlib:sodium_dust",
		temperature: 370.944,
		fluid: "mekanism:sodium",
		gas: "mekanism:sodium",
	},
	MAGNESIUM: {
		name: "magnesium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/magnesium",
		normal_ores: [
		],
		color: "EDADEC",
		chemical: "magnesium",
		ingot: "moremekanismprocessing:magnesium_ingot",
		nugget: "moremekanismprocessing:magnesium_nugget",
		block: "chemlib:magnesium_metal_block",
		plate: "chemlib:magnesium_plate",
		dust: "moremekanismprocessing:dust_magnesium",
		temperature: 923.0,
		fluid: "kubejs:magnesium",
		gas: "kubejs:magnesium",
	},
	ALUMINUM: {
		name: "aluminum",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/aluminum",
		normal_ores: [
		],
		color: "D9D9D9",
		chemical: "aluminum",
		ingot: "moremekanismprocessing:aluminum_ingot",
		nugget: "moremekanismprocessing:aluminum_nugget",
		block: "chemlib:aluminum_metal_block",
		plate: "chemlib:aluminum_plate",
		dust: "moremekanismprocessing:dust_aluminum",
		clean_slurry: "moremekanismprocessing:clean_aluminum",
		dirty_slurry: "moremekanismprocessing:dirty_aluminum",
		temperature: 933.47,
		fluid: "kubejs:aluminum",
		gas: "kubejs:aluminum",
	},
	POTASSIUM: {
		name: "potassium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/potassium",
		normal_ores: [
		],
		color: "c6985f",
		chemical: "potassium",
		ingot: "chemlib:potassium_ingot",
		nugget: "chemlib:potassium_nugget",
		block: "chemlib:potassium_metal_block",
		plate: "chemlib:potassium_plate",
		dust: "chemlib:potassium_dust",
		temperature: 336.7,
		fluid: "kubejs:potassium",
		gas: "kubejs:potassium",
	},
	CALCIUM: {
		name: "calcium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/calcium",
		normal_ores: [
		],
		color: "dbd2c7",
		chemical: "calcium",
		ingot: "chemlib:calcium_ingot",
		nugget: "chemlib:calcium_nugget",
		block: "chemlib:calcium_metal_block",
		plate: "chemlib:calcium_plate",
		dust: "chemlib:calcium_dust",
		temperature: 1115.0,
		fluid: "kubejs:calcium",
		gas: "kubejs:calcium",
	},
	SCANDIUM: {
		name: "scandium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/scandium",
		normal_ores: [
		],
		color: "fcff63",
		chemical: "scandium",
		ingot: "chemlib:scandium_ingot",
		nugget: "chemlib:scandium_nugget",
		block: "chemlib:scandium_metal_block",
		plate: "chemlib:scandium_plate",
		dust: "chemlib:scandium_dust",
		temperature: 1814.0,
		fluid: "kubejs:scandium",
		gas: "kubejs:scandium",
	},
	TITANIUM: {
		name: "titanium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/titanium",
		normal_ores: [
		],
		no_ore_processing: true,
		color: "6375ff",
		chemical: "titanium",
		ingot: "moremekanismprocessing:titanium_ingot",
		nugget: "moremekanismprocessing:titanium_nugget",
		block: "chemlib:titanium_metal_block",
		plate: "chemlib:titanium_plate",
		dust: "moremekanismprocessing:dust_titanium",
		clean_slurry: "moremekanismprocessing:clean_titanium",
		dirty_slurry: "moremekanismprocessing:dirty_titanium",
		temperature: 1941.0,
		fluid: "kubejs:titanium",
		gas: "kubejs:titanium",
	},
	VANADIUM: {
		name: "vanadium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/vanadium",
		normal_ores: [
		],
		color: "647689",
		chemical: "vanadium",
		ingot: "chemlib:vanadium_ingot",
		nugget: "chemlib:vanadium_nugget",
		block: "chemlib:vanadium_metal_block",
		plate: "chemlib:vanadium_plate",
		dust: "chemlib:vanadium_dust",
		temperature: 2183.0,
		fluid: "kubejs:vanadium",
		gas: "kubejs:vanadium",
	},
	CHROMIUM: {
		name: "chromium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/chromium",
		normal_ores: [
		],
		color: "481a5d",
		chemical: "chromium",
		ingot: "chemlib:chromium_ingot",
		nugget: "chemlib:chromium_nugget",
		block: "chemlib:chromium_metal_block",
		plate: "chemlib:chromium_plate",
		dust: "chemlib:chromium_dust",
		temperature: 2180.0,
		fluid: "kubejs:chromium",
		gas: "kubejs:chromium",
	},
	MANGANESE: {
		name: "manganese",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/manganese",
		normal_ores: [
		],
		color: "c7a385",
		chemical: "manganese",
		ingot: "chemlib:manganese_ingot",
		nugget: "chemlib:manganese_nugget",
		block: "chemlib:manganese_metal_block",
		plate: "chemlib:manganese_plate",
		dust: "chemlib:manganese_dust",
		temperature: 1519.0,
		fluid: "kubejs:manganese",
		gas: "kubejs:manganese",
	},
	IRON: {
		name: "iron",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/iron",
		normal_ores: [
			"minecraft:iron_ore",
			"minecraft:deepslate_iron_ore",
			"ad_astra:moon_iron_ore",
			"ad_astra:mars_iron_ore",
			"ad_astra:mercury_iron_ore",
			"ad_astra:glacio_iron_ore",
			"deeperdarker:sculk_stone_iron_ore",
			"deeperdarker:gloomslate_iron_ore",
			"undergarden:depthrock_iron_ore",
			"undergarden:shiverstone_iron_ore",
		],
		color: "34302e",
		chemical: "iron",
		ingot: "minecraft:iron_ingot",
		nugget: "minecraft:iron_nugget",
		block: "minecraft:iron_block",
		raw: "minecraft:raw_iron",
		raw_block: "minecraft:raw_iron_block",
		plate: "thermal:iron_plate",
		gear: "thermal:iron_gear",
		dust: "mekanism:dust_iron",
		clean_slurry: "mekanism:clean_iron",
		dirty_slurry: "mekanism:dirty_iron",
		temperature: 1811.0,
		fluid: "kubejs:iron",
		gas: "kubejs:iron",
		enriched: "mekanism:enriched_iron",
		crystal: "mekanism:crystal_iron",
		dirty: "mekanism:dirty_dust_iron",
		clump: "mekanism:clump_iron",
		shard: "mekanism:shard_iron",
		chestplate: "minecraft:iron_chestplate",
		leggings: "minecraft:iron_leggings",
		helmet: "minecraft:iron_helmet",
		boots: "minecraft:iron_boots",
		sword: "minecraft:iron_sword",
		pickaxe: "minecraft:iron_pickaxe",
		hoe: "minecraft:iron_hoe",
		axe: "minecraft:iron_axe",
		shovel: "minecraft:iron_shovel",
	},
	COBALT: {
		name: "cobalt",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/cobalt",
		normal_ores: [
		],
		color: "6666FF",
		chemical: "cobalt",
		ingot: "moremekanismprocessing:cobalt_ingot",
		nugget: "moremekanismprocessing:cobalt_nugget",
		block: "chemlib:cobalt_metal_block",
		plate: "chemlib:cobalt_plate",
		dust: "moremekanismprocessing:dust_cobalt",
		clean_slurry: "moremekanismprocessing:clean_cobalt",
		dirty_slurry: "moremekanismprocessing:dirty_cobalt",
		temperature: 1768.0,
		fluid: "kubejs:cobalt",
		gas: "kubejs:cobalt",
	},
	COPPER: {
		name: "copper",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/copper",
		normal_ores: [
			"minecraft:copper_ore",
			"minecraft:deepslate_copper_ore",
			"ad_astra:glacio_copper_ore",
			"deeperdarker:sculk_stone_copper_ore",
			"deeperdarker:gloomslate_copper_ore",
		],
		color: "956853",
		chemical: "copper",
		ingot: "minecraft:copper_ingot",
		nugget: "thermal:copper_nugget",
		block: "minecraft:copper_block",
		raw: "minecraft:raw_copper",
		raw_block: "minecraft:raw_copper_block",
		plate: "thermal:copper_plate",
		gear: "thermal:copper_gear",
		dust: "mekanism:dust_copper",
		clean_slurry: "mekanism:clean_copper",
		dirty_slurry: "mekanism:dirty_copper",
		temperature: 1357.77,
		fluid: "kubejs:copper",
		gas: "kubejs:copper",
		crystal: "mekanism:crystal_copper",
		dirty: "mekanism:dirty_dust_copper",
		clump: "mekanism:clump_copper",
		shard: "mekanism:shard_copper",
	},
	ZINC: {
		name: "zinc",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/zinc",
		normal_ores: [
		],
		color: "a0997d",
		chemical: "zinc",
		ingot: "moremekanismprocessing:zinc_ingot",
		nugget: "moremekanismprocessing:zinc_nugget",
		block: "chemlib:zinc_metal_block",
		plate: "chemlib:zinc_plate",
		dust: "moremekanismprocessing:dust_zinc",
		clean_slurry: "moremekanismprocessing:clean_zinc",
		dirty_slurry: "moremekanismprocessing:dirty_zinc",
		infusion: "kubejs:zinc",
		temperature: 692.68,
		fluid: "kubejs:zinc",
		gas: "kubejs:zinc",
	},
	GALLIUM: {
		name: "gallium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/gallium",
		normal_ores: [
		],
		color: "a1a8c1",
		chemical: "gallium",
		ingot: "chemlib:gallium_ingot",
		nugget: "chemlib:gallium_nugget",
		block: "chemlib:gallium_metal_block",
		plate: "chemlib:gallium_plate",
		dust: "chemlib:gallium_dust",
		temperature: 302.9146,
		fluid: "kubejs:gallium",
		gas: "kubejs:gallium",
	},
	RUBIDIUM: {
		name: "rubidium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/rubidium",
		normal_ores: [
		],
		color: "ee88fd",
		chemical: "rubidium",
		ingot: "chemlib:rubidium_ingot",
		nugget: "chemlib:rubidium_nugget",
		block: "chemlib:rubidium_metal_block",
		plate: "chemlib:rubidium_plate",
		dust: "chemlib:rubidium_dust",
		temperature: 312.45,
		fluid: "kubejs:rubidium",
		gas: "kubejs:rubidium",
	},
	STRONTIUM: {
		name: "strontium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/strontium",
		normal_ores: [
		],
		color: "536998",
		chemical: "strontium",
		ingot: "chemlib:strontium_ingot",
		nugget: "chemlib:strontium_nugget",
		block: "chemlib:strontium_metal_block",
		plate: "chemlib:strontium_plate",
		dust: "chemlib:strontium_dust",
		temperature: 1050.0,
		fluid: "mekanismelements:strontium",
		gas: "mekanismelements:strontium",
	},
	YTTRIUM: {
		name: "yttrium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/yttrium",
		normal_ores: [
		],
		color: "b366c4",
		chemical: "yttrium",
		ingot: "chemlib:yttrium_ingot",
		nugget: "chemlib:yttrium_nugget",
		block: "chemlib:yttrium_metal_block",
		plate: "chemlib:yttrium_plate",
		dust: "chemlib:yttrium_dust",
		temperature: 1799.0,
		fluid: "mekanismelements:yttrium",
		gas: "mekanismelements:yttrium",
	},
	ZIRCONIUM: {
		name: "zirconium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/zirconium",
		normal_ores: [
		],
		color: "d3bb8f",
		chemical: "zirconium",
		ingot: "chemlib:zirconium_ingot",
		nugget: "chemlib:zirconium_nugget",
		block: "chemlib:zirconium_metal_block",
		plate: "chemlib:zirconium_plate",
		dust: "chemlib:zirconium_dust",
		temperature: 2128.0,
		fluid: "kubejs:zirconium",
		gas: "kubejs:zirconium",
	},
	NIOBIUM: {
		name: "niobium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/niobium",
		normal_ores: [
		],
		color: "734d54",
		chemical: "niobium",
		ingot: "chemlib:niobium_ingot",
		nugget: "chemlib:niobium_nugget",
		block: "chemlib:niobium_metal_block",
		plate: "chemlib:niobium_plate",
		dust: "chemlib:niobium_dust",
		temperature: 2750.0,
		fluid: "kubejs:niobium",
		gas: "kubejs:niobium",
	},
	MOLYBDENUM: {
		name: "molybdenum",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/molybdenum",
		normal_ores: [
		],
		color: "6d7e9a",
		chemical: "molybdenum",
		ingot: "chemlib:molybdenum_ingot",
		nugget: "chemlib:molybdenum_nugget",
		block: "chemlib:molybdenum_metal_block",
		plate: "chemlib:molybdenum_plate",
		dust: "chemlib:molybdenum_dust",
		temperature: 2896.0,
		fluid: "kubejs:molybdenum",
		gas: "kubejs:molybdenum",
	},
	RUTHENIUM: {
		name: "ruthenium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/ruthenium",
		normal_ores: [
		],
		color: "715f63",
		chemical: "ruthenium",
		ingot: "chemlib:ruthenium_ingot",
		nugget: "chemlib:ruthenium_nugget",
		block: "chemlib:ruthenium_metal_block",
		plate: "chemlib:ruthenium_plate",
		dust: "chemlib:ruthenium_dust",
		temperature: 2607.0,
		fluid: "kubejs:ruthenium",
		gas: "kubejs:ruthenium",
	},
	RHODIUM: {
		name: "rhodium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/rhodium",
		normal_ores: [
		],
		color: "827569",
		chemical: "rhodium",
		ingot: "chemlib:rhodium_ingot",
		nugget: "chemlib:rhodium_nugget",
		block: "chemlib:rhodium_metal_block",
		plate: "chemlib:rhodium_plate",
		dust: "chemlib:rhodium_dust",
		temperature: 2237.0,
		fluid: "kubejs:rhodium",
		gas: "kubejs:rhodium",
	},
	PALLADIUM: {
		name: "palladium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/palladium",
		normal_ores: [
		],
		color: "704158",
		chemical: "palladium",
		ingot: "chemlib:palladium_ingot",
		nugget: "chemlib:palladium_nugget",
		block: "chemlib:palladium_metal_block",
		plate: "chemlib:palladium_plate",
		dust: "chemlib:palladium_dust",
		temperature: 1828.05,
		fluid: "kubejs:palladium",
		gas: "kubejs:palladium",
	},
	SILVER: {
		name: "silver",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/silver",
		normal_ores: [
			"thermal_and_space:glacio_silver_ore",
			"thermal_and_space:mars_silver_ore",
			"thermal_and_space:mercury_silver_ore",
			"thermal_and_space:moon_silver_ore",
			"thermal_and_space:venus_silver_ore",
			"thermal:silver_ore",
			"thermal:deepslate_silver_ore",
		],
		color: "c1c7c7",
		chemical: "silver",
		ingot: "thermal:silver_ingot",
		nugget: "thermal:silver_nugget",
		block: "thermal:silver_block",
		raw: "thermal:raw_silver",
		raw_block: "thermal:raw_silver_block",
		plate: "thermal:silver_plate",
		gear: "thermal:silver_gear",
		dust: "thermal:silver_dust",
		clean_slurry: "moremekanismprocessing:clean_silver",
		dirty_slurry: "moremekanismprocessing:dirty_silver",
		temperature: 1234.93,
		fluid: "kubejs:silver",
		gas: "kubejs:silver",
		crystal: "moremekanismprocessing:crystal_silver",
		dirty: "moremekanismprocessing:dirty_dust_silver",
		clump: "moremekanismprocessing:clump_silver",
		shard: "moremekanismprocessing:shard_silver",
	},
	CADMIUM: {
		name: "cadmium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/cadmium",
		normal_ores: [
		],
		color: "9a2b34",
		chemical: "cadmium",
		ingot: "chemlib:cadmium_ingot",
		nugget: "chemlib:cadmium_nugget",
		block: "chemlib:cadmium_metal_block",
		plate: "chemlib:cadmium_plate",
		dust: "chemlib:cadmium_dust",
		temperature: 594.22,
		fluid: "kubejs:cadmium",
		gas: "kubejs:cadmium",
	},
	INDIUM: {
		name: "indium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/indium",
		normal_ores: [
		],
		color: "86847f",
		chemical: "indium",
		ingot: "chemlib:indium_ingot",
		nugget: "chemlib:indium_nugget",
		block: "chemlib:indium_metal_block",
		plate: "chemlib:indium_plate",
		dust: "chemlib:indium_dust",
		temperature: 429.7485,
		fluid: "kubejs:indium",
		gas: "kubejs:indium",
	},
	TIN: {
		name: "tin",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/tin",
		normal_ores: [
			"thermal_and_space:glacio_tin_ore",
			"thermal_and_space:mars_tin_ore",
			"thermal_and_space:mercury_tin_ore",
			"thermal_and_space:moon_tin_ore",
			"thermal_and_space:venus_tin_ore",
			"mekanism:tin_ore",
			"mekanism:deepslate_tin_ore",
			"mekanismaaa:moon_tin_ore",
			"mekanismaaa:mars_tin_ore",
			"mekanismaaa:glacio_tin_ore",
		],
		color: "46311a",
		chemical: "tin",
		ingot: "mekanism:ingot_tin",
		nugget: "mekanism:nugget_tin",
		block: "mekanism:block_tin",
		raw: "mekanism:raw_tin",
		raw_block: "mekanism:block_raw_tin",
		plate: "thermal:tin_plate",
		gear: "thermal:tin_gear",
		dust: "mekanism:dust_tin",
		clean_slurry: "mekanism:clean_tin",
		dirty_slurry: "mekanism:dirty_tin",
		infusion: "mekanism:tin",
		temperature: 505.08,
		fluid: "kubejs:tin",
		gas: "kubejs:tin",
		enriched: "mekanism:enriched_tin",
		crystal: "mekanism:crystal_tin",
		dirty: "mekanism:dirty_dust_tin",
		clump: "mekanism:clump_tin",
		shard: "mekanism:shard_tin",
	},
	CESIUM: {
		name: "cesium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/cesium",
		normal_ores: [
		],
		color: "cbac2a",
		chemical: "cesium",
		ingot: "chemlib:cesium_ingot",
		nugget: "chemlib:cesium_nugget",
		block: "chemlib:cesium_metal_block",
		plate: "chemlib:cesium_plate",
		dust: "chemlib:cesium_dust",
		temperature: 301.7,
		fluid: "kubejs:cesium",
		gas: "kubejs:cesium",
	},
	BARIUM: {
		name: "barium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/barium",
		normal_ores: [
		],
		color: "c7bca8",
		chemical: "barium",
		ingot: "chemlib:barium_ingot",
		nugget: "chemlib:barium_nugget",
		block: "chemlib:barium_metal_block",
		plate: "chemlib:barium_plate",
		dust: "chemlib:barium_dust",
		temperature: 1000.0,
		fluid: "kubejs:barium",
		gas: "kubejs:barium",
	},
	LANTHANUM: {
		name: "lanthanum",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/lanthanum",
		normal_ores: [
		],
		color: "ba9160",
		chemical: "lanthanum",
		ingot: "chemlib:lanthanum_ingot",
		nugget: "chemlib:lanthanum_nugget",
		block: "chemlib:lanthanum_metal_block",
		plate: "chemlib:lanthanum_plate",
		dust: "chemlib:lanthanum_dust",
		temperature: 1193.0,
		fluid: "kubejs:lanthanum",
		gas: "kubejs:lanthanum",
	},
	CERIUM: {
		name: "cerium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/cerium",
		normal_ores: [
		],
		color: "662c5e",
		chemical: "cerium",
		ingot: "chemlib:cerium_ingot",
		nugget: "chemlib:cerium_nugget",
		block: "chemlib:cerium_metal_block",
		plate: "chemlib:cerium_plate",
		dust: "chemlib:cerium_dust",
		temperature: 1068.0,
		fluid: "kubejs:cerium",
		gas: "kubejs:cerium",
	},
	PRASEODYMIUM: {
		name: "praseodymium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/praseodymium",
		normal_ores: [
		],
		color: "73b93d",
		chemical: "praseodymium",
		ingot: "chemlib:praseodymium_ingot",
		nugget: "chemlib:praseodymium_nugget",
		block: "chemlib:praseodymium_metal_block",
		plate: "chemlib:praseodymium_plate",
		dust: "chemlib:praseodymium_dust",
		temperature: 1208.0,
		fluid: "kubejs:praseodymium",
		gas: "kubejs:praseodymium",
	},
	NEODYMIUM: {
		name: "neodymium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/neodymium",
		normal_ores: [
		],
		color: "8c696b",
		chemical: "neodymium",
		ingot: "chemlib:neodymium_ingot",
		nugget: "chemlib:neodymium_nugget",
		block: "chemlib:neodymium_metal_block",
		plate: "chemlib:neodymium_plate",
		dust: "chemlib:neodymium_dust",
		temperature: 1297.0,
		fluid: "kubejs:neodymium",
		gas: "kubejs:neodymium",
	},
	SAMARIUM: {
		name: "samarium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/samarium",
		normal_ores: [
		],
		color: "b7b05c",
		chemical: "samarium",
		ingot: "chemlib:samarium_ingot",
		nugget: "chemlib:samarium_nugget",
		block: "chemlib:samarium_metal_block",
		plate: "chemlib:samarium_plate",
		dust: "chemlib:samarium_dust",
		temperature: 1345.0,
		fluid: "kubejs:samarium",
		gas: "kubejs:samarium",
	},
	EUROPIUM: {
		name: "europium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/europium",
		normal_ores: [
		],
		color: "ce81b3",
		chemical: "europium",
		ingot: "chemlib:europium_ingot",
		nugget: "chemlib:europium_nugget",
		block: "chemlib:europium_metal_block",
		plate: "chemlib:europium_plate",
		dust: "chemlib:europium_dust",
		temperature: 1099.0,
		fluid: "kubejs:europium",
		gas: "kubejs:europium",
	},
	GADOLINIUM: {
		name: "gadolinium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/gadolinium",
		normal_ores: [
		],
		color: "915536",
		chemical: "gadolinium",
		ingot: "chemlib:gadolinium_ingot",
		nugget: "chemlib:gadolinium_nugget",
		block: "chemlib:gadolinium_metal_block",
		plate: "chemlib:gadolinium_plate",
		dust: "chemlib:gadolinium_dust",
		temperature: 1585.0,
		fluid: "kubejs:gadolinium",
		gas: "kubejs:gadolinium",
	},
	TERBIUM: {
		name: "terbium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/terbium",
		normal_ores: [
		],
		color: "8ba754",
		chemical: "terbium",
		ingot: "chemlib:terbium_ingot",
		nugget: "chemlib:terbium_nugget",
		block: "chemlib:terbium_metal_block",
		plate: "chemlib:terbium_plate",
		dust: "chemlib:terbium_dust",
		temperature: 1629.0,
		fluid: "kubejs:terbium",
		gas: "kubejs:terbium",
	},
	DYSPROSIUM: {
		name: "dysprosium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/dysprosium",
		normal_ores: [
		],
		color: "653f0e",
		chemical: "dysprosium",
		ingot: "chemlib:dysprosium_ingot",
		nugget: "chemlib:dysprosium_nugget",
		block: "chemlib:dysprosium_metal_block",
		plate: "chemlib:dysprosium_plate",
		dust: "chemlib:dysprosium_dust",
		temperature: 1680.0,
		fluid: "kubejs:dysprosium",
		gas: "kubejs:dysprosium",
	},
	HOLMIUM: {
		name: "holmium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/holmium",
		normal_ores: [
		],
		color: "4d6352",
		chemical: "holmium",
		ingot: "chemlib:holmium_ingot",
		nugget: "chemlib:holmium_nugget",
		block: "chemlib:holmium_metal_block",
		plate: "chemlib:holmium_plate",
		dust: "chemlib:holmium_dust",
		temperature: 1734.0,
		fluid: "kubejs:holmium",
		gas: "kubejs:holmium",
	},
	ERBIUM: {
		name: "erbium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/erbium",
		normal_ores: [
		],
		color: "a05768",
		chemical: "erbium",
		ingot: "chemlib:erbium_ingot",
		nugget: "chemlib:erbium_nugget",
		block: "chemlib:erbium_metal_block",
		plate: "chemlib:erbium_plate",
		dust: "chemlib:erbium_dust",
		temperature: 1802.0,
		fluid: "kubejs:erbium",
		gas: "kubejs:erbium",
	},
	THULIUM: {
		name: "thulium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/thulium",
		normal_ores: [
		],
		color: "179e43",
		chemical: "thulium",
		ingot: "chemlib:thulium_ingot",
		nugget: "chemlib:thulium_nugget",
		block: "chemlib:thulium_metal_block",
		plate: "chemlib:thulium_plate",
		dust: "chemlib:thulium_dust",
		temperature: 1818.0,
		fluid: "kubejs:thulium",
		gas: "kubejs:thulium",
	},
	YTTERBIUM: {
		name: "ytterbium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/ytterbium",
		normal_ores: [
		],
		color: "e7e39f",
		chemical: "ytterbium",
		ingot: "chemlib:ytterbium_ingot",
		nugget: "chemlib:ytterbium_nugget",
		block: "chemlib:ytterbium_metal_block",
		plate: "chemlib:ytterbium_plate",
		dust: "chemlib:ytterbium_dust",
		temperature: 1097.0,
		fluid: "kubejs:ytterbium",
		gas: "kubejs:ytterbium",
	},
	LUTETIUM: {
		name: "lutetium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/lutetium",
		normal_ores: [
		],
		color: "954d41",
		chemical: "lutetium",
		ingot: "chemlib:lutetium_ingot",
		nugget: "chemlib:lutetium_nugget",
		block: "chemlib:lutetium_metal_block",
		plate: "chemlib:lutetium_plate",
		dust: "chemlib:lutetium_dust",
		temperature: 1925.0,
		fluid: "kubejs:lutetium",
		gas: "kubejs:lutetium",
	},
	HAFNIUM: {
		name: "hafnium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/hafnium",
		normal_ores: [
		],
		color: "243267",
		chemical: "hafnium",
		ingot: "chemlib:hafnium_ingot",
		nugget: "chemlib:hafnium_nugget",
		block: "chemlib:hafnium_metal_block",
		plate: "chemlib:hafnium_plate",
		dust: "chemlib:hafnium_dust",
		temperature: 2506.0,
		fluid: "kubejs:hafnium",
		gas: "kubejs:hafnium",
	},
	TANTALUM: {
		name: "tantalum",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/tantalum",
		normal_ores: [
		],
		color: "a81e20",
		chemical: "tantalum",
		ingot: "chemlib:tantalum_ingot",
		nugget: "chemlib:tantalum_nugget",
		block: "chemlib:tantalum_metal_block",
		plate: "chemlib:tantalum_plate",
		dust: "chemlib:tantalum_dust",
		temperature: 3290.0,
		fluid: "kubejs:tantalum",
		gas: "kubejs:tantalum",
	},
	TUNGSTEN: {
		name: "tungsten",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/tungsten",
		normal_ores: [
		],
		color: "2b313e",
		chemical: "tungsten",
		ingot: "moremekanismprocessing:tungsten_ingot",
		nugget: "moremekanismprocessing:tungsten_nugget",
		block: "chemlib:tungsten_metal_block",
		plate: "chemlib:tungsten_plate",
		dust: "moremekanismprocessing:dust_tungsten",
		clean_slurry: "moremekanismprocessing:clean_tungsten",
		dirty_slurry: "moremekanismprocessing:dirty_tungsten",
		temperature: 3695.0,
		fluid: "kubejs:tungsten",
		gas: "kubejs:tungsten",
	},
	RHENIUM: {
		name: "rhenium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/rhenium",
		normal_ores: [
		],
		color: "1b1d1b",
		chemical: "rhenium",
		ingot: "chemlib:rhenium_ingot",
		nugget: "chemlib:rhenium_nugget",
		block: "chemlib:rhenium_metal_block",
		plate: "chemlib:rhenium_plate",
		dust: "chemlib:rhenium_dust",
		temperature: 3459.0,
		fluid: "kubejs:rhenium",
		gas: "kubejs:rhenium",
	},
	OSMIUM: {
		name: "osmium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/osmium",
		normal_ores: [
			"mekanism:osmium_ore",
			"mekanism:deepslate_osmium_ore",
			"mekanismaaa:mercury_osmium_ore",
			"mekanismaaa:moon_osmium_ore",
			"mekanismaaa:glacio_osmium_ore",
		],
		color: "7599c1",
		chemical: "osmium",
		ingot: "mekanism:ingot_osmium",
		nugget: "mekanism:nugget_osmium",
		block: "mekanism:block_osmium",
		raw: "mekanism:raw_osmium",
		raw_block: "mekanism:block_raw_osmium",
		plate: "chemlib:osmium_plate",
		dust: "mekanism:dust_osmium",
		clean_slurry: "mekanism:clean_osmium",
		dirty_slurry: "mekanism:dirty_osmium",
		temperature: 3306.0,
		fluid: "kubejs:osmium",
		gas: "mekanism:osmium",
		enriched: "mekanism_extras:enriched_osmium",
		crystal: "mekanism:crystal_osmium",
		dirty: "mekanism:dirty_dust_osmium",
		clump: "mekanism:clump_osmium",
		shard: "mekanism:shard_osmium",
		chestplate: "mekanismtools:osmium_chestplate",
		leggings: "mekanismtools:osmium_leggings",
		helmet: "mekanismtools:osmium_helmet",
		boots: "mekanismtools:osmium_boots",
		sword: "mekanismtools:osmium_sword",
		pickaxe: "mekanismtools:osmium_pickaxe",
		hoe: "mekanismtools:osmium_hoe",
		axe: "mekanismtools:osmium_axe",
		shovel: "mekanismtools:osmium_shovel",
	},
	IRIDIUM: {
		name: "iridium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/iridium",
		normal_ores: [
		],
		color: "2f5eef",
		chemical: "iridium",
		ingot: "moremekanismprocessing:iridium_ingot",
		nugget: "moremekanismprocessing:iridium_nugget",
		block: "chemlib:iridium_metal_block",
		plate: "chemlib:iridium_plate",
		dust: "moremekanismprocessing:dust_iridium",
		clean_slurry: "moremekanismprocessing:clean_iridium",
		dirty_slurry: "moremekanismprocessing:dirty_iridium",
		temperature: 2719.0,
		fluid: "kubejs:iridium",
		gas: "kubejs:iridium",
	},
	PLATINUM: {
		name: "platinum",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/platinum",
		normal_ores: [
		],
		color: "d2d3d3",
		chemical: "platinum",
		ingot: "moremekanismprocessing:platinum_ingot",
		nugget: "moremekanismprocessing:platinum_nugget",
		block: "chemlib:platinum_metal_block",
		plate: "chemlib:platinum_plate",
		dust: "moremekanismprocessing:dust_platinum",
		clean_slurry: "moremekanismprocessing:clean_platinum",
		dirty_slurry: "moremekanismprocessing:dirty_platinum",
		temperature: 2041.4,
		fluid: "kubejs:platinum",
		gas: "kubejs:platinum",
	},
	GOLD: {
		name: "gold",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/gold",
		normal_ores: [
			"minecraft:gold_ore",
			"minecraft:deepslate_gold_ore",
			"minecraft:nether_gold_ore",
			"ad_astra:venus_gold_ore",
			"deeperdarker:sculk_stone_gold_ore",
			"deeperdarker:gloomslate_gold_ore",
			"undergarden:depthrock_gold_ore",
		],
		color: "cfac38",
		chemical: "gold",
		ingot: "minecraft:gold_ingot",
		nugget: "minecraft:gold_nugget",
		block: "minecraft:gold_block",
		raw: "minecraft:raw_gold",
		raw_block: "minecraft:raw_gold_block",
		plate: "thermal:gold_plate",
		gear: "thermal:gold_gear",
		dust: "mekanism:dust_gold",
		clean_slurry: "mekanism:clean_gold",
		dirty_slurry: "mekanism:dirty_gold",
		infusion: "mekanism:gold",
		temperature: 1337.33,
		fluid: "kubejs:gold",
		gas: "kubejs:gold",
		enriched: "mekanism:enriched_gold",
		crystal: "mekanism:crystal_gold",
		dirty: "mekanism:dirty_dust_gold",
		clump: "mekanism:clump_gold",
		shard: "mekanism:shard_gold",
		chestplate: "minecraft:golden_chestplate",
		leggings: "minecraft:golden_leggings",
		helmet: "minecraft:golden_helmet",
		boots: "minecraft:golden_boots",
		sword: "minecraft:golden_sword",
		pickaxe: "minecraft:golden_pickaxe",
		hoe: "minecraft:golden_hoe",
		axe: "minecraft:golden_axe",
		shovel: "minecraft:golden_shovel",
	},
	THALLIUM: {
		name: "thallium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/thallium",
		normal_ores: [
		],
		color: "785445",
		chemical: "thallium",
		ingot: "chemlib:thallium_ingot",
		nugget: "chemlib:thallium_nugget",
		block: "chemlib:thallium_metal_block",
		plate: "chemlib:thallium_plate",
		dust: "chemlib:thallium_dust",
		temperature: 577.0,
		fluid: "kubejs:thallium",
		gas: "kubejs:thallium",
	},
	LEAD: {
		name: "lead",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/lead",
		normal_ores: [
			"thermal_and_space:glacio_lead_ore",
			"thermal_and_space:mars_lead_ore",
			"thermal_and_space:mercury_lead_ore",
			"thermal_and_space:moon_lead_ore",
			"thermal_and_space:venus_lead_ore",
			"mekanism:lead_ore",
			"mekanism:deepslate_lead_ore",
			"mekanismaaa:venus_lead_ore",
			"mekanismaaa:mercury_lead_ore",
			"mekanismaaa:glacio_lead_ore",
		],
		color: "34465a",
		chemical: "lead",
		ingot: "mekanism:ingot_lead",
		nugget: "mekanism:nugget_lead",
		block: "mekanism:block_lead",
		raw: "mekanism:raw_lead",
		raw_block: "mekanism:block_raw_lead",
		plate: "thermal:lead_plate",
		gear: "thermal:lead_gear",
		dust: "mekanism:dust_lead",
		clean_slurry: "mekanism:clean_lead",
		dirty_slurry: "mekanism:dirty_lead",
		infusion: "mekanism_extras:lead",
		temperature: 600.61,
		fluid: "kubejs:lead",
		gas: "kubejs:lead",
		enriched: "mekanism_extras:enriched_lead",
		crystal: "mekanism:crystal_lead",
		dirty: "mekanism:dirty_dust_lead",
		clump: "mekanism:clump_lead",
		shard: "mekanism:shard_lead",
	},
	BISMUTH: {
		name: "bismuth",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/bismuth",
		normal_ores: [
		],
		color: "3d9185",
		chemical: "bismuth",
		ingot: "moremekanismprocessing:bismuth_ingot",
		nugget: "moremekanismprocessing:bismuth_nugget",
		block: "chemlib:bismuth_metal_block",
		plate: "chemlib:bismuth_plate",
		dust: "moremekanismprocessing:dust_bismuth",
		clean_slurry: "moremekanismprocessing:clean_bismuth",
		dirty_slurry: "moremekanismprocessing:dirty_bismuth",
		temperature: 544.7,
		fluid: "kubejs:bismuth",
		gas: "kubejs:bismuth",
	},
	POLONIUM: {
		name: "polonium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/polonium",
		normal_ores: [
		],
		color: "29443f",
		chemical: "polonium",
		ingot: "chemlib:polonium_ingot",
		nugget: "chemlib:polonium_nugget",
		block: "chemlib:polonium_metal_block",
		plate: "chemlib:polonium_plate",
		dust: "chemlib:polonium_dust",
		temperature: 527.0,
		fluid: "kubejs:polonium",
		gas: "mekanism:polonium",
	},
	FRANCIUM: {
		name: "francium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/francium",
		normal_ores: [
		],
		color: "9a410c",
		chemical: "francium",
		ingot: "chemlib:francium_ingot",
		nugget: "chemlib:francium_nugget",
		block: "chemlib:francium_metal_block",
		plate: "chemlib:francium_plate",
		dust: "chemlib:francium_dust",
		temperature: 300.0,
		fluid: "kubejs:francium",
		gas: "kubejs:francium",
	},
	RADIUM: {
		name: "radium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/radium",
		normal_ores: [
		],
		color: "3c9c6f",
		chemical: "radium",
		ingot: "chemlib:radium_ingot",
		nugget: "chemlib:radium_nugget",
		block: "chemlib:radium_metal_block",
		plate: "chemlib:radium_plate",
		dust: "chemlib:radium_dust",
		temperature: 1233.0,
		fluid: "kubejs:radium",
		gas: "kubejs:radium",
	},
	ACTINIUM: {
		name: "actinium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/actinium",
		normal_ores: [
		],
		color: "7781f9",
		chemical: "actinium",
		ingot: "chemlib:actinium_ingot",
		nugget: "chemlib:actinium_nugget",
		block: "chemlib:actinium_metal_block",
		plate: "chemlib:actinium_plate",
		dust: "chemlib:actinium_dust",
		temperature: 1500.0,
		fluid: "kubejs:actinium",
		gas: "kubejs:actinium",
	},
	THORIUM: {
		name: "thorium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/thorium",
		normal_ores: [
		],
		color: "5f4533",
		chemical: "thorium",
		ingot: "moremekanismprocessing:thorium_ingot",
		nugget: "moremekanismprocessing:thorium_nugget",
		block: "chemlib:thorium_metal_block",
		plate: "chemlib:thorium_plate",
		dust: "moremekanismprocessing:dust_thorium",
		temperature: 2023.0,
		fluid: "kubejs:thorium",
		gas: "kubejs:thorium",
	},
	PROTACTINIUM: {
		name: "protactinium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/protactinium",
		normal_ores: [
		],
		color: "3e8863",
		chemical: "protactinium",
		ingot: "chemlib:protactinium_ingot",
		nugget: "chemlib:protactinium_nugget",
		block: "chemlib:protactinium_metal_block",
		plate: "chemlib:protactinium_plate",
		dust: "chemlib:protactinium_dust",
		temperature: 1841.0,
		fluid: "kubejs:protactinium",
		gas: "kubejs:protactinium",
	},
	URANIUM: {
		name: "uranium",
		amount: 1.0,
		metal: true,
		upgrade: false,
		normal_ores_tag: "#forge:ores/uranium",
		normal_ores: [
			"mekanism:deepslate_uranium_ore",
		],
		color: "d1c33e",
		chemical: "uranium",
		ingot: "mekanism:ingot_uranium",
		nugget: "mekanism:nugget_uranium",
		block: "mekanism:block_uranium",
		raw: "mekanism:raw_uranium",
		raw_block: "mekanism:block_raw_uranium",
		plate: "chemlib:uranium_plate",
		dust: "mekanism:dust_uranium",
		clean_slurry: "mekanism:clean_uranium",
		dirty_slurry: "mekanism:dirty_uranium",
		temperature: 1405.3,
		fluid: "kubejs:uranium",
		gas: "kubejs:uranium",
		crystal: "mekanism:crystal_uranium",
		dirty: "mekanism:dirty_dust_uranium",
		clump: "mekanism:clump_uranium",
		shard: "mekanism:shard_uranium",
	},
}