// priority: 3
const CHEM_ELEMENTS_TO_CREATE = [
	{
		id: "boron",
		color: 4082272,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 3274.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "carbon",
		color: 2631720,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 4061.5,
		matter_state: "solid",
		combustion: 110.5,
	},
	{
		id: "fluorine",
		color: 11850059,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 69.255,
		matter_state: "gas",
		combustion: null,
	},
	{
		id: "neon",
		color: 16038951,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 25.832,
		matter_state: "gas",
		combustion: null,
	},
	{
		id: "magnesium",
		color: 15576556,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1143.0,
		matter_state: "solid",
		combustion: 601.6,
	},
	{
		id: "aluminum",
		color: 14277081,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1838.2350000000001,
		matter_state: "solid",
		combustion: 837.85,
	},
	{
		id: "silicon",
		color: 11383417,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2612.5,
		matter_state: "solid",
		combustion: 9055.0,
	},
	{
		id: "phosphorus",
		color: 14140298,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 435.45000000000005,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "sulfur",
		color: 11904272,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 553.0799999999999,
		matter_state: "solid",
		combustion: 296.81,
	},
	{
		id: "argon",
		color: 6754723,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 85.55600000000001,
		matter_state: "gas",
		combustion: null,
	},
	{
		id: "potassium",
		color: 13015135,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 684.35,
		matter_state: "solid",
		combustion: 182.0,
	},
	{
		id: "calcium",
		color: 14406343,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1436.0,
		matter_state: "solid",
		combustion: 635.0,
	},
	{
		id: "scandium",
		color: 16580451,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2461.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "titanium",
		color: 6518271,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2750.5,
		matter_state: "solid",
		combustion: 760.44,
	},
	{
		id: "vanadium",
		color: 6583945,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2931.5,
		matter_state: "solid",
		combustion: 775.3,
	},
	{
		id: "chromium",
		color: 4725341,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2562.0,
		matter_state: "solid",
		combustion: 589.3,
	},
	{
		id: "manganese",
		color: 13083525,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1926.5,
		matter_state: "solid",
		combustion: 520.0,
	},
	{
		id: "iron",
		color: 3420206,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2472.5,
		matter_state: "solid",
		combustion: 272.04,
	},
	{
		id: "cobalt",
		color: 6711039,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2484.0,
		matter_state: "solid",
		combustion: 237.74,
	},
	{
		id: "nickel",
		color: 6452812,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2365.5,
		matter_state: "solid",
		combustion: 240.0,
	},
	{
		id: "copper",
		color: 9791571,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2096.385,
		matter_state: "solid",
		combustion: 156.0,
	},
	{
		id: "zinc",
		color: 10525053,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 936.3399999999999,
		matter_state: "solid",
		combustion: 0.27,
	},
	{
		id: "gallium",
		color: 10594497,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1487.9573,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "germanium",
		color: 13423808,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2158.7,
		matter_state: "solid",
		combustion: 536.0,
	},
	{
		id: "arsenic",
		color: 9191217,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 988.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "selenium",
		color: 490625,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 726.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "krypton",
		color: 12378863,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 117.855,
		matter_state: "gas",
		combustion: null,
	},
	{
		id: "rubidium",
		color: 15632637,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 636.725,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "zirconium",
		color: 13876111,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 3389.0,
		matter_state: "solid",
		combustion: 1097.46,
	},
	{
		id: "niobium",
		color: 7556436,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 3883.5,
		matter_state: "solid",
		combustion: 949.77,
	},
	{
		id: "molybdenum",
		color: 7175834,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 3904.0,
		matter_state: "solid",
		combustion: 745.1,
	},
	{
		id: "technetium",
		color: 7701641,
		need_gas: true,
		need_fluid: true,
		radiation: 1,
		temperature: 3484.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "ruthenium",
		color: 7429987,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 3515.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "rhodium",
		color: 8549737,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 3102.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "palladium",
		color: 7356760,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2532.025,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "silver",
		color: 12699591,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1834.9650000000001,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cadmium",
		color: 10103604,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 817.11,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "indium",
		color: 8815743,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1387.37425,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "tin",
		color: 4600090,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1690.04,
		matter_state: "solid",
		combustion: 577.63,
	},
	{
		id: "antimony",
		color: 8738672,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1405.8899999999999,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "tellurium",
		color: 2579226,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 991.8299999999999,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cesium",
		color: 13347882,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 622.85,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "barium",
		color: 13089960,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1559.0,
		matter_state: "solid",
		combustion: 582.0,
	},
	{
		id: "lanthanum",
		color: 12226912,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2465.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cerium",
		color: 6696030,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2392.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "praseodymium",
		color: 7584061,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2305.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "neodymium",
		color: 9202027,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2322.0,
		matter_state: "solid",
		combustion: 903.95,
	},
	{
		id: "promethium",
		color: 103477415,
		need_gas: true,
		need_fluid: true,
		radiation: 20840,
		temperature: 2294.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "samarium",
		color: 12038236,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1759.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "europium",
		color: 13533619,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1450.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "gadolinium",
		color: 9524534,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2429.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "terbium",
		color: 9152340,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2512.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "dysprosium",
		color: 6635278,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2260.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "holmium",
		color: 5071698,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2303.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "erbium",
		color: 10508136,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2471.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "thulium",
		color: 1547843,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2020.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "ytterbium",
		color: 15197087,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1283.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "lutetium",
		color: 9784641,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2800.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "hafnium",
		color: 2372199,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 3691.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "tantalum",
		color: 11017760,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 4510.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "tungsten",
		color: 2830654,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 4949.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "rhenium",
		color: 1776923,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 4664.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "osmium",
		color: 7707073,
		need_gas: false,
		need_fluid: true,
		radiation: 0,
		temperature: 4295.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "iridium",
		color: 3104495,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 3561.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "platinum",
		color: 13816787,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 3069.7,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "gold",
		color: 13610040,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2290.165,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "mercury",
		color: 10330015,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: null,
	},
	{
		id: "thallium",
		color: 7885893,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1161.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "lead",
		color: 3425882,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1311.305,
		matter_state: "solid",
		combustion: 274.47,
	},
	{
		id: "bismuth",
		color: 4034949,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1190.85,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "polonium",
		color: 2704447,
		need_gas: false,
		need_fluid: true,
		radiation: 3618,
		temperature: 881.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "astatine",
		color: 10470419,
		need_gas: true,
		need_fluid: true,
		radiation: 45858,
		temperature: 592.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "radon",
		color: 6279530,
		need_gas: true,
		need_fluid: true,
		radiation: 96618,
		temperature: 206.75,
		matter_state: "gas",
		combustion: null,
	},
	{
		id: "francium",
		color: 10109196,
		need_gas: true,
		need_fluid: true,
		radiation: 17050,
		temperature: 625.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "radium",
		color: 3972207,
		need_gas: true,
		need_fluid: true,
		radiation: 233,
		temperature: 1621.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "actinium",
		color: 7832057,
		need_gas: true,
		need_fluid: true,
		radiation: 16956,
		temperature: 2500.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "thorium",
		color: 6243635,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 3542.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "protactinium",
		color: 4098147,
		need_gas: true,
		need_fluid: true,
		radiation: 11,
		temperature: 3070.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "uranium",
		color: 13747006,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2904.65,
		matter_state: "solid",
		combustion: 1191.6666666666667,
	},
	{
		id: "neptunium",
		color: 6647909,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2679.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "plutonium",
		color: 14380578,
		need_gas: false,
		need_fluid: true,
		radiation: 0,
		temperature: 2208.75,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "americium",
		color: 11239488,
		need_gas: false,
		need_fluid: true,
		radiation: 50,
		temperature: 2164.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "curium",
		color: 9568563,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2498.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "berkelium",
		color: 11832129,
		need_gas: true,
		need_fluid: true,
		radiation: 267,
		temperature: 2079.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "californium",
		color: 11825480,
		need_gas: true,
		need_fluid: true,
		radiation: 410,
		temperature: 1458.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "einsteinium",
		color: 2062766,
		need_gas: true,
		need_fluid: true,
		radiation: 285889,
		temperature: 1201.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "fermium",
		color: 14929313,
		need_gas: true,
		need_fluid: true,
		radiation: 3675,
		temperature: 1980.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "mendelevium",
		color: 1381044,
		need_gas: true,
		need_fluid: true,
		radiation: 7172,
		temperature: 1210.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "nobelium",
		color: 8274408,
		need_gas: true,
		need_fluid: true,
		radiation: 132990,
		temperature: 1210.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "lawrencium",
		color: 9013900,
		need_gas: true,
		need_fluid: true,
		radiation: 36941,
		temperature: 2090.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "rutherfordium",
		color: 3355190,
		need_gas: true,
		need_fluid: true,
		radiation: 28295,
		temperature: 4100.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "dubnium",
		color: 11237983,
		need_gas: true,
		need_fluid: true,
		radiation: 66495,
		temperature: 4000.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "seaborgium",
		color: 16208672,
		need_gas: true,
		need_fluid: true,
		radiation: 189986,
		temperature: 4000.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "bohrium",
		color: 5552265,
		need_gas: true,
		need_fluid: true,
		radiation: 246279,
		temperature: 4000.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "hassium",
		color: 9079121,
		need_gas: true,
		need_fluid: true,
		radiation: 332477,
		temperature: 138.6,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "meitnerium",
		color: 7298362,
		need_gas: true,
		need_fluid: true,
		radiation: 12313,
		temperature: 4000.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "darmstadtium",
		color: 3300006,
		need_gas: true,
		need_fluid: true,
		radiation: 92354,
		temperature: 4000.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "roentgenium",
		color: 8435784,
		need_gas: true,
		need_fluid: true,
		radiation: 36941,
		temperature: 4000.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "copernicium",
		color: 14914377,
		need_gas: true,
		need_fluid: true,
		radiation: 9235,
		temperature: 2677.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "nihonium",
		color: 6160393,
		need_gas: true,
		need_fluid: true,
		radiation: 18470,
		temperature: 1065.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "flerovium",
		color: 6637189,
		need_gas: true,
		need_fluid: true,
		radiation: 280571,
		temperature: 380.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "moscovium",
		color: 1634989,
		need_gas: true,
		need_fluid: true,
		radiation: 369419,
		temperature: 1035.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "livermorium",
		color: 4750651,
		need_gas: true,
		need_fluid: true,
		radiation: 3078,
		temperature: 897.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "tennessine",
		color: 11572799,
		need_gas: true,
		need_fluid: true,
		radiation: 7388,
		temperature: 803.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "oganesson",
		color: 7487175,
		need_gas: true,
		need_fluid: true,
		radiation: 73883,
		temperature: 262.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "carbon_dioxide",
		color: 3328050,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1402.016,
		matter_state: "gas",
		combustion: null,
	},
	{
		id: "ethylene",
		color: 13027231,
		need_gas: false,
		need_fluid: true,
		radiation: 0,
		temperature: 136.75,
		matter_state: "gas",
		combustion: 519.1899999999999,
	},
	{
		id: "cellulose",
		color: 12430222,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1185.7940476190474,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "chitin",
		color: 3151373,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1227.6414444444445,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "keratin",
		color: 3151373,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 30.40559917510311,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "silicon_dioxide",
		color: 8418401,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2603.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "nitrate",
		color: 6272454,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 71.768625,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "potassium_nitrate",
		color: 13015135,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 151.223725,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "aluminum_oxide",
		color: 10527454,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 778.6584,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "magnesium_oxide",
		color: 15577773,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 3497.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "sodium_chloride",
		color: 13091233,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1379.9,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "kaolinite",
		color: 10788826,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 390.0552,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "protein",
		color: 9464853,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 164.9615,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "iron_oxide",
		color: 7872544,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1032.3644,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "sucrose",
		color: 14734802,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 818.8114444444444,
		matter_state: "solid",
		combustion: 5647.0,
	},
	{
		id: "carbonate",
		color: 6386010,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1069.5805,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "calcium_carbonate",
		color: 9937244,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1095.9641000000001,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "phosphate",
		color: 13605203,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 144.9092,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "hydroxide",
		color: 16756224,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 44.70225,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "hydroxylapatite",
		color: 11721138,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 208.68871025641027,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "strontium_carbonate",
		color: 13522968,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1162.7640999999999,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "beryl",
		color: 11654847,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 934.6690344827587,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "starch",
		color: 16576422,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1185.7940476190474,
		matter_state: "solid",
		combustion: 17.484,
	},
	{
		id: "cucurbitacin",
		color: 16762880,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1563.0944523809521,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "zinc_oxide",
		color: 12436621,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2438.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cobalt_aluminate",
		color: 1143494,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 921.3665714285714,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "triglyceride",
		color: 13158490,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1419.2254615384616,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "lead_iodide",
		color: 14075443,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 914.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "ethanol",
		color: 13826710,
		need_gas: true,
		need_fluid: false,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: 1367.0,
	},
	{
		id: "amide",
		color: 13826810,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 34.837833333333336,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "urea",
		color: 15134900,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 483.299125,
		matter_state: "solid",
		combustion: 0.6327,
	},
	{
		id: "ammonium",
		color: 11860730,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 27.7549,
		matter_state: "gas",
		combustion: null,
	},
	{
		id: "diammonium_phosphate",
		color: 13826710,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 13.596843750000001,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "potassium_carbonate",
		color: 13015135,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 849.2200833333334,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "mullite",
		color: 7237270,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 320.02436923076925,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "ethane",
		color: 13114930,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 137.5,
		matter_state: "gas",
		combustion: 1560.0,
	},
	{
		id: "propane",
		color: 6561330,
		need_gas: true,
		need_fluid: false,
		radiation: 0,
		temperature: 158.305,
		matter_state: "gas",
		combustion: 2220.0,
	},
	{
		id: "butane",
		color: 7313076,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 206.5,
		matter_state: "gas",
		combustion: 2877.0,
	},
	{
		id: "pentane",
		color: 7312981,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: 3509.0,
	},
	{
		id: "hexane",
		color: 7327026,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: 4.163,
	},
	{
		id: "graphite",
		color: 2039583,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 4061.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "calcium_sulfide",
		color: 2039583,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2017.7,
		matter_state: "solid",
		combustion: 458.59999999999997,
	},
	{
		id: "potassium_dichromate",
		color: 15238982,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 722.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "nickel_chloride",
		color: 6137715,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 925.4033333333334,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "potassium_permanganate",
		color: 9658293,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 567.0626666666667,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "magnesium_sulfate",
		color: 11509677,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 901.9626666666667,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "copper_chloride",
		color: 6009724,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1084.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cadmium_sulfide",
		color: 13025851,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1635.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "chromium_oxide",
		color: 8629089,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 3489.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "antimony_trioxide",
		color: 16449480,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 605.7203999999999,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "titanium_oxide",
		color: 3284530,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1143.5644,
		matter_state: "solid",
		combustion: 369.1199999999999,
	},
	{
		id: "han_purple",
		color: 14443775,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 931.4029,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "arsenic_sulfide",
		color: 16409730,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 770.79,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "barium_sulfate",
		color: 11914202,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1860.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "beta_carotene",
		color: 16747560,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1702.2844583333335,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "polyvinyl_chloride",
		color: 14134950,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 928.16025,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "epinephrine",
		color: 15114360,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: null,
	},
	{
		id: "acetylsalicylic_acid",
		color: 8568575,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1760.9352380952382,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "caffeine",
		color: 6579220,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 986.5938749999999,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "mercury_sulfide",
		color: 10109271,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 763.42,
		matter_state: "solid",
		combustion: 238.81,
	},
	{
		id: "sodium_hydroxide",
		color: 13878915,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1128.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "calcium_oxide",
		color: 14406343,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 3003.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "calcium_hydroxide",
		color: 14406343,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 613.2459,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "calcium_chloride",
		color: 14406343,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1628.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "sodium_carbonate",
		color: 13878915,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 849.90175,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "magnesium_carbonate",
		color: 15577773,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 562.0641,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "lead_oxide",
		color: 12224449,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 691.7895000000001,
		matter_state: "solid",
		combustion: 55.06000000000003,
	},
	{
		id: "lead_sulfide",
		color: 12224449,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1470.0,
		matter_state: "solid",
		combustion: 415.82000000000005,
	},
	{
		id: "zinc_sulfide",
		color: 12436621,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1534.45,
		matter_state: "solid",
		combustion: 778.4,
	},
	{
		id: "iron_disulfide",
		color: 8421504,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1192.8866666666668,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "tin_oxide",
		color: 8692174,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 611.5293333333334,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "manganese_oxide",
		color: 14793458,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 823.0626666666667,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "strontium_oxide",
		color: 13522968,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 711.137,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "iron_ii_oxide",
		color: 3092271,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2668.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "sodium_bisulfate",
		color: 13878915,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 459.8,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "ammonium_chloride",
		color: 3963100,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 338.6290833333333,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "phosphoric_acid",
		color: 14771335,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 400.25,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "calcium_sulfate",
		color: 14406343,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1101.296,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "copper_i_oxide",
		color: 16751134,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1787.5,
		matter_state: "solid",
		combustion: 142.0,
	},
	{
		id: "copper_i_sulfide",
		color: 16751134,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1764.6333333333334,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "hydrogen_sulfide",
		color: 15784990,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 200.64999999999998,
		matter_state: "gas",
		combustion: 264.83,
	},
	{
		id: "acetylene",
		color: 9889310,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1176.21775,
		matter_state: "gas",
		combustion: 1300.0,
	},
	{
		id: "acetic_acid",
		color: 13168740,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: 0.874,
	},
	{
		id: "nickel_sulfide",
		color: 13016482,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1365.5,
		matter_state: "solid",
		combustion: 448.94999999999993,
	},
	{
		id: "antimony_trisulfide",
		color: 12686906,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1121.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "nickel_oxide",
		color: 13016482,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1887.297,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "carbon_monoxide",
		color: 4539987,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 74.865,
		matter_state: "gas",
		combustion: 0.283,
	},
	{
		id: "lithium_hydroxide",
		color: 2661974,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 966.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "rubidium_hydroxide",
		color: 998696,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1157.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cesium_hydroxide",
		color: 16749568,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 439.03825,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "beryllium_hydroxide",
		color: 12109792,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 448.0809,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "magnesium_hydroxide",
		color: 15577773,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 458.84590000000003,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "strontium_hydroxide",
		color: 13522968,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 895.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "barium_hydroxide",
		color: 56243,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 700.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "aluminum_hydroxide",
		color: 15557691,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 494.2634642857143,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "zinc_hydroxide",
		color: 12436621,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 328.0459,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "manganese_hydroxide",
		color: 14793458,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 450.9459,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cadmium_hydroxide",
		color: 10523507,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 488.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "copper_ii_hydroxide",
		color: 16751134,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 471.04589999999996,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "lithium_chloride",
		color: 2661974,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1271.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "rubidium_chloride",
		color: 998696,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1325.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cesium_chloride",
		color: 16749568,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1244.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "beryllium_chloride",
		color: 12109792,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 713.5,
		matter_state: "solid",
		combustion: 16.0,
	},
	{
		id: "magnesium_chloride",
		color: 15577773,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1336.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "strontium_chloride",
		color: 13522968,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1333.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "barium_chloride",
		color: 56243,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1532.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "lithium_oxide",
		color: 2661974,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2290.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "sodium_oxide",
		color: 13878915,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1812.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "potassium_oxide",
		color: 13015135,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 864.0313333333334,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "rubidium_oxide",
		color: 998696,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 721.8646666666666,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "beryllium_oxide",
		color: 12109792,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2133.547,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "barium_oxide",
		color: 56243,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2233.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "lithium_carbonate",
		color: 2661974,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1288.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "rubidium_carbonate",
		color: 998696,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1140.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cesium_carbonate",
		color: 16749568,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 385.88008333333335,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "beryllium_carbonate",
		color: 12109792,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 350.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "barium_carbonate",
		color: 56243,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1402.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "manganese_carbonate",
		color: 14793458,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 634.1641,
		matter_state: "solid",
		combustion: 31.799999999999955,
	},
	{
		id: "iron_carbonate",
		color: 8421504,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 708.4160999999999,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cobalt_carbonate",
		color: 1143494,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 784.2641,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "nickel_carbonate",
		color: 13016482,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 653.5640999999999,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "copper_carbonate",
		color: 16751134,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 518.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "zinc_carbonate",
		color: 12436621,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 438.7641,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cadmium_carbonate",
		color: 10523507,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 377.33810000000005,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "lead_carbonate",
		color: 12224449,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 610.4641,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "lithium_sulfate",
		color: 2661974,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1391.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "sodium_sulfate",
		color: 13878915,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1429.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "potassium_sulfate",
		color: 13015135,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1652.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "rubidium_sulfate",
		color: 998696,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1645.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cesium_sulfate",
		color: 16749568,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 298.26800000000003,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "beryllium_sulfate",
		color: 12109792,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1576.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "strontium_sulfate",
		color: 13522968,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 365.36266666666666,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "manganese_sulfate",
		color: 14793458,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1051.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cobalt_sulfate",
		color: 1143494,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 860.546,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "nickel_sulfate",
		color: 13016482,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1198.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "iron_ii_sulfate",
		color: 8421504,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 827.546,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "copper_ii_sulfate",
		color: 16751134,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 653.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "zinc_sulfate",
		color: 12436621,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 981.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cadmium_sulfate",
		color: 10523507,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 811.546,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "lead_sulfate",
		color: 12224449,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 938.3793333333333,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "tin_sulfate",
		color: 8692174,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 654.9626666666667,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "lithium_nitrate",
		color: 2661974,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 700.5,
		matter_state: "solid",
		combustion: 25.5,
	},
	{
		id: "sodium_nitrate",
		color: 13878915,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 617.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "rubidium_nitrate",
		color: 998696,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 717.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cesium_nitrate",
		color: 16749568,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 138.923725,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "beryllium_nitrate",
		color: 12109792,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 374.3,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "magnesium_nitrate",
		color: 15577773,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 502.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "calcium_nitrate",
		color: 14406343,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 619.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "strontium_nitrate",
		color: 13522968,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 880.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "barium_nitrate",
		color: 56243,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 559.8310833333334,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "manganese_nitrate",
		color: 16759538,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 341.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "iron_iii_nitrate",
		color: 8421504,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 359.15,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cobalt_nitrate",
		color: 1143494,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 375.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "nickel_nitrate",
		color: 13016482,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 373.9,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "copper_nitrate",
		color: 16751134,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 415.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "zinc_nitrate",
		color: 12436621,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 390.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "lead_nitrate",
		color: 12224449,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 493.49775,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cadmium_nitrate",
		color: 10523507,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 519.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "aluminum_nitrate",
		color: 16215621,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 381.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "carbon_disulfide",
		color: 13138120,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: 1687.2,
	},
	{
		id: "potassium_ethyl_xanthate",
		color: 13138120,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 167.39348076923076,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "barium_sulfide",
		color: 56243,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1962.95,
		matter_state: "solid",
		combustion: 415.21999999999997,
	},
	{
		id: "aluminum_carbonate",
		color: 10527454,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2791.062857142857,
		matter_state: "solid",
		combustion: 4316.21,
	},
	{
		id: "yttrium_barium_copper_oxide",
		color: 12631227,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1274.0121538461538,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "carbon_trioxide",
		color: 3328050,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1069.5805,
		matter_state: "gas",
		combustion: null,
	},
	{
		id: "yttrium_carbonate",
		color: 11513775,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 586.4815357142857,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "yttrium_hydroxide",
		color: 12564587,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 376.4438214285715,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "titanium_carbide",
		color: 7764085,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 4260.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "sodium_sulfide",
		color: 16440733,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1229.4966666666667,
		matter_state: "solid",
		combustion: 445.6,
	},
	{
		id: "azanide",
		color: 13156828,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 34.837833333333336,
		matter_state: "gas",
		combustion: null,
	},
	{
		id: "p_phenylenediamine",
		color: 13156828,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1531.6998541666667,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "aniline",
		color: 14078389,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: 3.393,
	},
	{
		id: "benzene",
		color: 14078389,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: 3268.0,
	},
	{
		id: "ozone",
		color: 12112621,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 121.0,
		matter_state: "gas",
		combustion: null,
	},
	{
		id: "potassium_nitrite",
		color: 12301715,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 761.585,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "lead_dioxide",
		color: 12301715,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 648.5626666666667,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "salicylic_acid",
		color: 7755808,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: 3025.0,
	},
	{
		id: "carboxylic_acid",
		color: 7755808,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: null,
	},
	{
		id: "antimony_sulfate",
		color: 13417367,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 195.12268235294115,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "sulfate",
		color: 13417367,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 168.4352,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "antimony_acid",
		color: 13417367,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1405.8899999999999,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "antimonate",
		color: 13417367,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 338.9972,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "lead_antimonate",
		color: 15000617,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 354.76226153846153,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "antimony_pentaoxide",
		color: 11038002,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 294.54333333333335,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "acetic_anhydride",
		color: 5591626,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: null,
	},
	{
		id: "tungsten_carbide",
		color: 1118481,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 4686.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "thallium_iii_oxide",
		color: 14540253,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1069.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "niobium_oxide",
		color: 13816530,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1342.6826666666666,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "niobium_pentoxide",
		color: 13816530,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1641.4242857142858,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "niobium_carbide",
		color: 13816530,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 4269.75,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "calcium_fluoride",
		color: 13816514,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2248.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "bismuth_iii_sulfide",
		color: 4801084,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 808.188,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "livingstonite",
		color: 10437180,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 827.268375,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "hydrazine",
		color: 11981557,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: 622.0,
	},
	{
		id: "sodium_hypochlorite",
		color: 14539407,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: null,
	},
	{
		id: "monochloramine",
		color: 14342543,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: null,
	},
	{
		id: "iron_iii_oxide_hydroxide",
		color: 7414291,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 647.3690624999999,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "orthoclase",
		color: 12685689,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 841.4059230769232,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "sodium_metasilicate",
		color: 11184810,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1190.562,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "potassium_aluminate",
		color: 10592673,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 666.7832500000001,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "zirconium_silicate",
		color: 9268564,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1619.3960000000002,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "enstatite",
		color: 5392640,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 794.4644000000001,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "ferrosilite",
		color: 4471364,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1060.3644,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "titanium_dioxide",
		color: 14998485,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2680.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "magnetite",
		color: 7960955,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1100.9422857142856,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "glutaric_acid",
		color: 15658734,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 422.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "iron_hydroxide",
		color: 131329,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 512.3809,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "chalcopyrite",
		color: 12893086,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1418.76125,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "copper_ii_oxide",
		color: 65793,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1934.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "covellite",
		color: 1714993,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1324.7325,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "villamaninite",
		color: 1714993,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1067.515,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "magnesium_orthosilicate",
		color: 14869218,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1553.1965714285716,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "gold_iii_oxide",
		color: 7153429,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 961.1564000000001,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "gold_i_sulfide",
		color: 5192502,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1457.1333333333334,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "gold_iii_sulfide",
		color: 5192502,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1247.914,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "gold_iii_chloride",
		color: 7153429,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 711.54125,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "gold_iii_hydroxide",
		color: 5656095,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 346.32453571428573,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "chloroauric_acid",
		color: 15448099,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 615.1425833333333,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "wollastonite",
		color: 11512483,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 853.0644,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "glucose",
		color: 11512483,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1042.00875,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "formic_acid",
		color: 11512483,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: 0.254,
	},
	{
		id: "tricalcium_phosphate",
		color: 8682851,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1186.7977230769231,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "phosphorus_pentoxide",
		color: 16777215,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 623.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "strontium_aluminate",
		color: 4259830,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 759.3665714285714,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "dolomite",
		color: 7697773,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1006.7641,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "manganese_ii_oxide",
		color: 15234931,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1715.047,
		matter_state: "solid",
		combustion: 135.0,
	},
	{
		id: "calaverite",
		color: 7496261,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1424.6083333333333,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "titanium_iii_chloride",
		color: 4261262,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 891.16625,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "titanium_ii_chloride",
		color: 65793,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1539.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "titanium_tetrachloride",
		color: 16777215,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: 182.0,
	},
	{
		id: "osmium_dioxide",
		color: 1513501,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1297.3960000000002,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "osmium_tetroxide",
		color: 12367527,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 358.1,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "ruthenium_iv_oxide",
		color: 1444694,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1187.62,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "triuranium_octoxide",
		color: 11776,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1495.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "thorium_dioxide",
		color: 16777215,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 4145.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "thorium_monoxide",
		color: 1118481,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1807.1370000000002,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "aluminium_sulfate",
		color: 16512751,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 420.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "mercury_ii_chloride",
		color: 16777215,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 563.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "vanadium_v_oxide",
		color: 15846013,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1487.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "vanadium_iii_oxide",
		color: 11508572,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1868.0564,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "vanadium_iv_oxide",
		color: 65793,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1763.3960000000002,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "maleic_anhydride",
		color: 16777215,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1833.0092222222222,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "molybdenum_disulphide",
		color: 5986922,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2381.9333333333334,
		matter_state: "solid",
		combustion: 946.37,
	},
	{
		id: "molybdenum_trioxide",
		color: 9672614,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1251.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "molybdenum_dioxide",
		color: 6160525,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1533.7293333333332,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "perchlorate",
		color: 592137,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: null,
	},
	{
		id: "perchloric_acid",
		color: 592137,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: null,
	},
	{
		id: "ammonium_perchlorate",
		color: 3750201,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 250.42057,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "barium_perchlorate",
		color: 10066329,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 366.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "potassium_perchlorate",
		color: 6908265,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 130.54003333333333,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cobalt_ii_perchlorate",
		color: 11223589,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 377.8611272727273,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "lithium_perchlorate",
		color: 11223589,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 606.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "magnesium_perchlorate",
		color: 11184810,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 121.88912727272728,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "copper_ii_perchlorate",
		color: 2134219,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 374.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "sodium_perchlorate",
		color: 11184810,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 748.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "nitrosyl_perchlorate",
		color: 9079434,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 207.03681428571429,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "rubidium_perchlorate",
		color: 9079434,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 748.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "silver_perchlorate",
		color: 9079434,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 592.4143666666666,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "aluminium_chloride",
		color: 13816924,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 659.04125,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "chromium_trioxide",
		color: 5850441,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 496.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "sulfur_dichloride",
		color: 16714303,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: null,
	},
	{
		id: "phosgene",
		color: 16777215,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1136.121,
		matter_state: "gas",
		combustion: null,
	},
	{
		id: "thorium_iv_sulfide",
		color: 7361335,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2171.7666666666664,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "neodymium_iii_sulfate",
		color: 10507139,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 372.41562352941173,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "europium_ii_sulfate",
		color: 16775929,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 269.82253333333335,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "europium_ii_chloride",
		color: 15332842,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1735.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "europium_iii_chloride",
		color: 14935011,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 767.41625,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "lead_ii_chloride",
		color: 15395035,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 997.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "lead_iv_chloride",
		color: 10989174,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: null,
	},
	{
		id: "yttrium_iii_nitrate",
		color: 11184810,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 208.94660576923076,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "yttrium_iii_oxide",
		color: 11184810,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1043.7644,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "yttrium_iii_sulfate",
		color: 11184810,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 323.95915294117646,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cobalt_ii_hydroxide",
		color: 7885411,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 551.5459,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "sulfur_hexafluoride",
		color: 16776930,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 213.7,
		matter_state: "gas",
		combustion: null,
	},
	{
		id: "cobalt_ii_oxide",
		color: 8814450,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1925.547,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "cadmium_chloride",
		color: 10394520,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1039.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "antimony_trichloride",
		color: 11184810,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 421.55,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "antimony_oxychloride",
		color: 12167567,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 561.173,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "antimony_pentachloride",
		color: 15132110,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: null,
	},
	{
		id: "hydrogen_iodide",
		color: 12496830,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 230.07,
		matter_state: "gas",
		combustion: 116.41499999999999,
	},
	{
		id: "silver_nitrate",
		color: 10592673,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 597.9,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "silver_sulfate",
		color: 11580335,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1145.55,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "vanadium_carbide",
		color: 0,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 3496.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "disulfur_dichloride",
		color: 11103525,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: 535.46,
	},
	{
		id: "zinconat_cobalt",
		color: 299056,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 2438.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "sodium_fluoride",
		color: 16316134,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1621.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "hydrogen_peroxide",
		color: 14341593,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 303,
		matter_state: "liquid",
		combustion: null,
	},
	{
		id: "europium_ii_bromide",
		color: 14210257,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 682.7666666666667,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "europium_iii_bromide",
		color: 11974326,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 837.25,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "europium_iii_iodide",
		color: 7889946,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1086.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "europium_ii_iodide",
		color: 11179592,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1086.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "europium_iii_sulfate",
		color: 12413579,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1450.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "europium_iii_hydroxide",
		color: 16773117,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 226.37239285714287,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "europium_iii_oxide",
		color: 16777215,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 3505.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "europium_ii_oxide",
		color: 12795309,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 761.387,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "carbonic_acid",
		color: 4473924,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 310.0,
		matter_state: "gas",
		combustion: null,
	},
	{
		id: "hydrogen_bromide",
		color: 16773118,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 196.25,
		matter_state: "gas",
		combustion: 106.785,
	},
	{
		id: "niobium_v_chloride",
		color: 13158209,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 499.54999999999995,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "zirconium_dioxide",
		color: 10857854,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 3387.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "zirconium_iv_iodide",
		color: 15056159,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 738.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "zirconium_iv_chloride",
		color: 9600618,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 657.0,
		matter_state: "solid",
		combustion: 116.94000000000005,
	},
	{
		id: "zirconium_oxyhydroxide",
		color: 16777215,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 740.7205833333333,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "neodymium_iii_oxide",
		color: 12231109,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 3268.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "neodymium_iii_hydroxide",
		color: 12228540,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 350.87239285714287,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "neodymium_nitrate",
		color: 16592859,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 195.17737499999998,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "neodymium_iii_chloride",
		color: 14060741,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1451.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "sodium_tellurite",
		color: 15724527,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 811.8119999999999,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "tellurium_dioxide",
		color: 15327421,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1261.5,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "bismuth_iii_oxide",
		color: 13153577,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1625.0,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "sodium_sulfite",
		color: 14869218,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 305.1723333333333,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "bismuth_hydroxide",
		color: 14540253,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 189.27953571428571,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "bismuth_iii_sulfate",
		color: 14342874,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 496.09209411764704,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "metasilicic_acid",
		color: 2171169,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 477.2638333333333,
		matter_state: "gas",
		combustion: null,
	},
	{
		id: "sodium_orthosilicate",
		color: 13290186,
		need_gas: true,
		need_fluid: true,
		radiation: 0,
		temperature: 1119.0062222222223,
		matter_state: "solid",
		combustion: null,
	},
	{
		id: "stackoverflowium",
		color: 63973,
		need_gas: true,
		need_fluid: true,
		radiation: 1000,
		temperature: 1.5,
		matter_state: "gas",
		combustion: 1048576,
	},
	{
		id: "stackunderflowium",
		color: 14751484,
		need_gas: true,
		need_fluid: true,
		radiation: 1000,
		temperature: 1.5,
		matter_state: "gas",
		combustion: 1048576,
	},
	{
		id: "unknown",
		color: 0,
		need_gas: true,
		need_fluid: true,
		radiation: 1000,
		temperature: 1.5,
		matter_state: "gas",
		combustion: 1073741824,
	},
]